### ISSUE TITLE
floating window does not clear itself when changing buffers

### ISSUE THREAD

**Issue by sunjon** [pwntester/octo.nvim#1]
When a new buffer is loaded into a window, the floating window showing labels, assignees, etc is not removed.

**Comment by pwntester** [comment]
Hi!

Thanks for report, I have -- hopefully -- fix this. Can you please verify? If not, how are you loading the new buffer? I found that telescope's builtin for buffers does not trigger BufEnter when switching to a new buffer which is weird and need to investigate further. Other than that, it seems to work fine for me now.

**Comment by sunjon** [comment]
I'm still seeing the issue when I switch buffers using telescope buffer picker.

I  noticed that you'd opened an issue specifically concerning the autocommands with the picker that's probably related.
Swiching buffer with telescope MRU picker seems to clear the windows fine.

**Comment by pwntester** [comment]
closing since Im not using floats anymore
