### ISSUE TITLE
Add commands to add/remove reactions

### ISSUE THREAD

**Issue by pwntester** [pwntester/octo.nvim#10]

**Comment by aikooo7** [comment]
Hey, looking at documentation and trying put eyes reaction in issue 12 and redoing the command it doesn't remove it.

**Comment by aikooo7** [comment]
Forgot to ping you since this is a closed issue. @pwntester

**Comment by pwntester** [comment]
Works for me. Im using `:Octo reaction eyes` when the cursor is located in a comment. Retyping the same command gets the reaction removed

**Comment by aikooo7** [comment]
I tried it now and can confirm it works, sorry for the confusion.
