### ISSUE TITLE
Feature request - have PR review converstations in the PR buffer

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#100]
After a review is done it is cumbersome to have conversations only by viewing the PRs review (`Octo pr reviews`). As the stubs of the conversations are already in the PR buffer, it would be amazing to extend this with the whole content. If you could then add "comments" to these review conversations would be even better. The same for resolving them.

These features would fit well as addition:
- using folds for the reviews conversations
- using foating windows to preview the code snippet that the conversation relates to

**Comment by pwntester** [comment]
Thinking about this one, how would you differentiate the PR comments from the thread comments? It would be nice if we could indent them as its done in the web UI but I dont think that would be possible.

**Comment by tami5** [comment]
:+1: I always disliked not being able to see those type of comments. Maybe different color for the comment or something to make obvious

**Comment by weilbith** [comment]
I would like to have both options. So indent them, put something in their header (as already now) and also add new highlight groups for them. You still link these groups to the already existing comment groups.
And depending on how you add (later) the code snippet, this will become even more distinguishable.

**Comment by weilbith** [comment]
I would like to have both options. So indent them, put something in their header (as already now) and also add new highlight groups for them. You still link these groups to the already existing comment groups.
And depending on how you add (later) the code snippet, this will become even more distinguishable.

**Comment by weilbith** [comment]
I just realized that the content of the comments themselves are Markdown. So the different highlighting is little bit more tricky and initially thought.

**Comment by pwntester** [comment]
Yep, not an easy solution, but I will check if there is anything we can do with new virtual text overlays

**Comment by weilbith** [comment]
Next to the indentation on the left side of the buffer, maybe you could limit the width of the review conversation threads? This combined with folds and some header highlighting sounds quite good to me.

**Comment by pwntester** [comment]
Started implementing this at #105 

I dont see any way of indenting the comments and vim does not support soft wrapping, so UI may not be optimal :(
