### ISSUE TITLE
Feature request - extend in-buffer edits

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#101]
Hey, :upside_down_face: 
I already confessed that I have issues to remember all the bindings and commands. And actually really like your nice approach to make the buffer as itself editable and apply changes by writing it. And I was wondering if this could be extended. E.g. for the header of the issue to add/remove assignees and reviewers. This reminds me of editing e-mail header in NeoVim when I write a message via NeoMutt.
I guess for labels this does not work as this is a selection of the existing labels. But maybe this could be improved by allowing to remove labels and even add labels by automatically open the completion pop-up menu when going into insert mode at the labels header line? Another extension would be reactions to comments which basically works exactly the same. Just that atm the reactions line is only shown if there are any reactions. To always enable to add an initial reaction it would be required to have it permanently here like for an unset header.

Looking forward to the discussions about the suggested feature details. :hugs:

**Comment by pwntester** [comment]
Not sure about this one, all those details line are really virtual text, so we would need to render them as regular text which make it possible to make mistakes, unintentional deletions, etc. Perhaps we can use the new overlay feature to add the labels and allow editing only the values by using some leading spaces. Lets keep it open for now and see if we can find a good way to implement this.

**Comment by weilbith** [comment]
Hmm. I see the complexity.
I'm pretty impressed how you do the buffer-write-feature anyway. No clue how this works. On a first sight it appears very complex and nasty to handle. But I should start dig a bit into the code to understand your approach and architecture. Eventually this enables me to come up with some proposals how to do it more easily (the new suggestions I mean). Because I still think this would be pretty cool. :laughing:

**Comment by pwntester** [comment]
I basically use virtual text for headers which should not be editable. I use extmarks to keep track of where comments start and end so I can use things like sign column to visualize them.
Would be great if you could get familiar with the code to help with some contributions in the future!

**Comment by pwntester** [comment]
Im closing this for now since Im not planning on implementing this on any near future. Basically, assignees, reviewers, labels are better picked from menus so you dont have to remember exact user or label names. We may need to think on how to make commands and bindings more easily rememberable. Maybe adding completion for second level of commands.
