### ISSUE TITLE
Feature request - pop-up window for comments during a review

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#107]
If I have added a comment to a line of code during a review, I can see the highlight of the line and the sign in the sign column. But how can I inspect my comment again? I can only go to `Octo review comments`. But there I first have to find it again between all comments I have already added. I would love to have a quick solution for the location I'm currently at.

**Comment by pwntester** [comment]
Yep showing it on CursorHold makes sense

**Comment by pwntester** [comment]
This got implemented in #122
