### ISSUE TITLE
Feature request - assist the user which lines he can select for review comments/suggestions

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#108]
When I select lines to comment or make a suggestion for, I sometimes get errors because the selection was too big. GH only allows to select lines somehow relative to changed hunks. For the user this is not obvious to see and know what he can select and what not. It would be cool if we could figure out an approach how to assist the user here. But I don't know if such information is actually available.
If it should be possible to somehow get this information which lines are selectable, my proposal would be to add a sign into the sign column for these lines. Something super simple like a bar in the color of the change (added, changed, ...).

**Comment by pwntester** [comment]
Implemented in #6ee8741
