### ISSUE TITLE
Feature request - correctly detect what the user can edit/delete and communicate that

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#114]
At the moment all issue/PR titles, bodies, comments etc. are shown as editable to the user. Also the user can go into insert mode to edit them. If he then saves the buffer the errors bubble up. 
It should be possible to determine what the user can edit via `viewerCanDelete` and `viewerCanUpdate`. Such items should not been marked as editable (coloring) and the insert mode should be blocked as well as all other not editable parts of the buffer.

**Comment by pwntester** [comment]
Im currently communicating that with a red dot:

<img width="803" alt="image" src="https://user-images.githubusercontent.com/125701/111710331-c4c27300-8849-11eb-9a80-3c4d16ef42cd.png">

I don't think there is a way to prevent editing of comments though.

I can intercept InsertEnter and exit back to Normal mode if the cursor is on non-editable regions. But I don't think there is a way to prevent normal mode commands (eg: `dd`)

I thought about using virtual text, but then that text won't be searchable :(

**Comment by weilbith** [comment]
l actually thought that we could eventually get rid of the extmarks for non editable parts, but at least remove the editable highlight by the signcolumn from all these comments? So that the signs are only used for the editable stuff. Is that not possible?

**Comment by pwntester** [comment]
That should be possible but I think it may get confusing and visually merge different comments and events. I will give it a try and see how it looks.

Another option is to use different colors in the sign column:
- white: non-editable
- red: modified editable area
- green: unmodified editable area (meaning it can be edited)

**Comment by weilbith** [comment]
What I like about your new idea is that it is configurable and I could for example "disable" it.
