### ISSUE TITLE
Feature request - add highlighting for own versus foreign content

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#115]
Taking the WebUI as inspiration it would be cool if the issues (in fact the bodies), (review-)comments and reactions could be highlighted differently when they are by the user himself.

**Comment by weilbith** [comment]
@pwntester I think this should be pretty easy first feature I could implement? It depends on how it should look like. But it should be very local change without much deep knowledge required.
Getting to the question: how should it looks like? I would propose to introduce some background highlighting for the whole object (similar to the colored box in the WebUI). At best the user sets this to a very subtile contrast to the normal background color.

**Comment by pwntester** [comment]
LGTM, let me know if you need any help understanding the code 😃

**Comment by weilbith** [comment]
I think the best solution for the highlighting is your sign-linehl-approach. I need to test how this works when having multiple signs on top of each other. Depending on that we might need to think of an alternative highlight approach.

**Comment by pwntester** [comment]
Maybe its enough with some highlight or text differences in the comment header
