### ISSUE TITLE
Support saving PR review comments

### ISSUE THREAD

**Issue by entropitor** [pwntester/octo.nvim#118]
Given github supports drafting Pull Requests through the API, it would be nice if the review comments are not saved in lua state but on the github side. This would allow for your editor to crash, pick off a PR you started online or vice versa

`addPullRequestReview` to create one (event is optional, not setting it should not publish the review yet)
`submitPullRequestReview` to finally submit a PR review

**Comment by pwntester** [comment]
> event is optional, not setting it should not publish the review yet

Great, didnt know that! This looks great to me although @weilbith wanted to work offline in the train :)

We can send `addPullRequestReview` in `Octo review start` (with empty draft `comments`). 
Then add new comments with `addPullRequestReviewComment` as user adds new comments. 
And finally `submitPullRequestReview` on `Octo review submit`

We would also need a new command (`Octo review pending`?) to retrieve "pending" reviews

**Comment by weilbith** [comment]
Wow. This sounds pretty amazing. I'm curious how this looks like at the GitHub side. Does that mean there are objects stored that are hidden in the UI if they don't have specific property set that they are finished or you are the author? :thinking:

One question would be you would handle the case that you don't have a internet connection but add a review comment. @pwntester if I understand your approach correctly this would not work anymore right? Or is there caching for objects that have not been synced yet? What would be then the trigger to sync them once internet is back, without having to finish the whole review?

**Comment by weilbith** [comment]
Maybe we could introduce a queue of objects that need to be pushed? The Queue entries could be extend with an identifier which would allow to replace them, if the object has changed again before it got handled by the queue. This queue could then handle the updates depending on if there is a network connection or not. And then for commands like to finish a review we have to flush the queue synchronously. So such an action which requires flushing would never succeed if there is no network connection and before all preceding data was pushed.

**Comment by pwntester** [comment]
> I'm curious how this looks like at the GitHub site

I think they appear with a yellow PENDING bubble

> Or is there caching for objects that have not been synced yet? 

We still need the lua state to draw the sign column, show the popup (when implemented) etc. So I would just add a "not synched" property to the stored comment table if `addPullRequestReviewComment` fails to know if I need to send it in the final `submitPullRequestReview`

> What would be then the trigger to sync them once internet is back, without having to finish the whole review?

Thats a different approach, but I think its out of scope for now. TBH I would remove offline support altogether

**Comment by pwntester** [comment]
> Maybe we could introduce a queue of objects that need to be pushed? The Queue entries could be extend with an identifier which would allow to replace them, if the object has changed again before it got handled by the queue. This queue could then handle the updates depending on if there is a network connection or not. And then for commands like to finish a review we have to flush the queue synchronously. So such an action which requires flushing would never succeed if there is no network connection and before all preceding data was pushed.
This would a big addition of logic to the plugin. Also we would need some kind of persistent for the queue. But after all I think this open up a complete new level of features for Octo.

That sounds great, do we have a volunteer? 😁

**Comment by weilbith** [comment]
Sorry. I edited and extended the comment a couple of times. Bad habit. :expressionless:
I agree. First drop the offline support (as I have also written in one of my comment updates) and then think about how we can add it later again. I think I can come up with a draft PR at some time for that. But I have so much more in mind which does not even has an issue yet. :see_no_evil:

**Comment by weilbith** [comment]
We should have an issue for better offline support somewhere. I think it was about having a left diff version local to benefit from LSP etc. Let's see how the offline topic looks as a whole.

**Comment by weilbith** [comment]
Just as a quick note to support this issue even more: unfortunately I must admit that for serious and big PR reviews I do for work I still hesitate to use Octo. I guess this will get better over time. But having the comments pushed as "draft" to GH and I know nothing gets lost and I theoretically can review my review in the WebUI just to be 100% secure would help a lot.

**Comment by entropitor** [comment]
> Wow. This sounds pretty amazing. I'm curious how this looks like at the GitHub site. Does that mean there are objects stored that are hidden in the UI if they don't have specific property set that they are finished or you are the author? 🤔

Yes that's how I figured it out. Try refreshing your page on github in the middle of a review. Or opening it in a different browser. It's sort of like a "draft" _pull request review_ that is not yet published.

**Comment by weilbith** [comment]
> Yes that's how I figured it out. Try refreshing your page on github in the middle of a review. Or opening it in a different browser. It's sort of like a "draft" pull request review that is not yet published.

I barely use multiple browsers for regular "work". So until know I was assuming it gets stored in your browser locally. :shrug: 
But yeah, pretty cool. :grimacing:

**Comment by pwntester** [comment]
@entropitor @weilbith this should be ready. can you please give #120 a spin?

**Comment by entropitor** [comment]
I'm getting 
> E382: Cannot write, 'buftype' option is set

Is it also normal that comments are now a popup instead of a split? (So copying code is no longer possible?)

**Comment by pwntester** [comment]
> E382: Cannot write, 'buftype' option is set

Can you go into normal mode when in the comment window and check the output of these commands?
- `autocmd BufWriteCmd octo://*`
- `echo &bt`
- `echo bufname()`

> Is it also normal that comments are now a popup instead of a split? (So copying code is no longer possible?)

Yep, we changed that although I had the same concerns. There were some problems with splitting the comment buffer consistently in the presence of quickfix-related plugins. Would be able to pop-up the comment window multiple times to edit the comment work for you?

@weilbith this is why I want to avoid floats for editing (also in the main issue/pr buffers)

**Comment by weilbith** [comment]
Sorry, I have a lot to do at work, so I had no time to test it yet. But I just wanna response to the floating window issue.
How was the flow working for you before? I assume the comment split window opened, then you jump back to the diff window, copy, jump to the comment window again and paste.
So what changed is the jumping, as you can simply jump to a floating window with the normal `:wincmd <command>` commands. I think there was non added for floating windows? So I use a plugin that makes that resolves the problem. But that is not of help here. So we could improve the Octo command to make a comment to jump to the open window if there is already one. And additionally we could consider to map `<C-z>` to jump to this window. It is originally for the preview window. We could just declare the comment window as the preview one (just an option) and it would just work.
Second I suppose the floating window location might not be optimal as it hides the line of interest? (As I said I haven't tried it yet). So this could be improved to put the anchor below the to comment line/selection. To handle issues like "the user is at the bottom of the window" , we could first move the line in the center of the window (`zz`). To not confuse the user about this movement we could visually highlight the line he selected (just "search" the line?!) so it is more obvious. Then there is always enough space to put a floating window below that line/selection.

I think we should consider to work on the last paragraph (placing the window properly an related stuff). Regarding the window jumping I think we can easily support the user to do so (as described). But there are also plenty of plugins and other options for the user to make jumping to floating windows easier.

After all we might want to leave the decision for the user. In exact make it a configuration option if he wants to use the split or the floating window. Even I have not tested it, I'm pretty sure I'll love this feature and want to use it. It is also helpful for times you don't habe a huge screen with high resolution and a split if 4 windows is too much for it.
Implementation wise this should be not much overhead to differ between split or float. Opening the window and returning the ID of it can be a conditional step where the actual logic gets outsourced with a generic interface. And all other improvements like making it the preview window or so would be completely independent and do actually work for any approach how the window gets opened. We could even allow the user to set a function himself that opens a window and returns the ID.

```

**Comment by weilbith** [comment]
More improvement ideas: automatically copy the line/selection to a (just `0` and make it configurable?) register. So you don't even need to jump around.

**Comment by pwntester** [comment]
> So I use a plugin that makes that resolves the problem.

What plugins do you use? 🤔 

> And additionally we could consider to use <C-w>z to jump to this window. It is originally for the preview window. We could just declare the comment window as the preview one (just an option) and it would just work.

Didnt know about preview window. Not sure we can use this feature though since we have 4 windows (header, header border, content and content border) but we should be able to enable some mechanism to hide all these 4 windows on demand and be able to show them again

> I think we should consider to work on the last paragraph (placing the window properly an related stuff). Regarding the window jumping I think we can easily support the user to do so (as described)

Sounds good to me

**Comment by entropitor** [comment]
> Can you go into normal mode when in the comment window and check the output of these commands?

I couldn't reproduce anymore.

> So what changed is the jumping, as you can simply jump to a floating window with the normal :wincmd <command> commands. I think there was non added for floating windows

How can you jump to a window using those? I've the impression the window also disapeared when I want to grab something to copy?

Anyway, this should probably be separate issue 😅

**Comment by weilbith** [comment]
>   >  So I use a plugin that makes that resolves the problem.

> What plugins do you use? thinking

[vim-choosewin](https://github.com/t9md/vim-choosewin)

> Didnt know about preview window. Not sure we can use this feature though since we have 4 windows (header, header border, content and content border) but we should be able to enable some mechanism to hide all these 4 windows on demand and be able to show them again

The only thing that this needs would be to `set previewwindow` on the respective window. That's it.

> >    I think we should consider to work on the last paragraph (placing the window properly an related stuff). Regarding the window jumping I think we can easily support the user to do so (as described)

> Sounds good to me

Should I open issues for the ideas?

> How can you jump to a window using those? I've the impression the window also disapeared when I want to grab something to copy?

You are right. Now as I tried it the comment window closes if I jump out. @pwntester maybe we could take care of this in #124 ? Or was there a good reason to auto-close the window in such a case?

**Comment by pwntester** [comment]
> vim-choosewin

Does it allow you to change to float window?

> The only thing that this needs would be to set previewwindow on the respective window. That's it.

I can do that, but `<C-w>z` which closes the preview window, does not trigger a `BufDelete` on its buffer for whatever reason. I'm relying on this autocmd to close the border window so as a result, `<C-w>z` does not close the border window

Also, Leaving a float open when changing to a different window may result in not being able to see the other windows. It would make more sense to enable a command to hide the window (close it but preserve the buffer) and unhide it (create a new window and restore the buffer)

> Should I open issues for the ideas?

Sure, let's move the conversation out of this closed issue

> Or was there a good reason to auto-close the window in such a case?

I find it hard to come back to the float window (`<C-w>P` helps but as I said before, using preview window has other inconvenient
