### ISSUE TITLE
Add @people completion

### ISSUE THREAD

**Issue by pwntester** [pwntester/octo.nvim#12]
`https://github.com/suggestions/issue/710584628?repository=telescope.nvim&user_id=nvim-lua&mention_suggester=1`
    - [repository contributors](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#list-repository-contributors)
    - issue author
    - comment authors
    - users already mentioned in comments or description

**Comment by pwntester** [comment]
No description provided.

**Comment by pwntester** [comment]
fixed in #56 by grabbing issue participants from graphql api

**Comment by Antonio-Bennett** [comment]
This is a test using Octo.nvim lol
