### ISSUE TITLE
Feature request - movement to go to next comment in issue buffer

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#123]
Well, the title basically states it all. Maybe we can just "abuse" the extmarks for that, taking the current location and search for the next header extmark.

**Comment by pwntester** [comment]
Implemented in https://github.com/pwntester/octo.nvim/commit/0c9c1523b160a8e1c7fb92128370f94f1c8548dc

**Comment by weilbith** [comment]
Can this be easily extended for reviews? I mean if I'm doing a review and have the diff view, could we have a similar movement command to go to the next comment that is pending or what ever?
Is this a complete new issue (I would assume so) or could it be a simple extension of the existing functionality you added here? 🤔

**Comment by pwntester** [comment]
Pending comments can still be reviewed with `Octo review comments`, but yep, a `]p`/`[p` mappings can be added to navigate through pending comments on the same file. Please file a new bug for it
