### ISSUE TITLE
Feature request - do not close comment window if API request fails

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#124]
I was just about to do another PR review for work in Octo. I wrote a quite long and important comment. I saved the buffer which made it close. The API request failed for an error I don't understand. But the worst part is that all my text is gone and I have to rewrite it.

My improvement proposals would be to:
  - do not close the comment window on save (I have the habit to save buffers automatically [means my hands just do it] it while I stop interacting with the editor because I'm thinking)
  - do not close the comment  window when the API request fails (this give the user the option to fix something [might be irrelevant], but as last resort he could copy it and go to the web-browser where it PR review should be pending)
  
@pwntester what do you think? The error was btw. the following: 
 ```
 E714: List required
gh: Parse error on "\\" (error) at [2, 227]
```

**Comment by pwntester** [comment]
I pushed an urgent fix for this which should:
- properly escape `"` and `\` in graphql double-quoted attributes
- do not automatically close the comment window on `:w`. Actually, you can save it as many times as you want and the comment will be updated in GH.

**Comment by weilbith** [comment]
Amazing. I haven't re-tried it yet, but thank you very much for fixing it so fast! :pray:
