### ISSUE TITLE
Improve Thread folding

### ISSUE THREAD

**Issue by pwntester** [pwntester/octo.nvim#125]
Currently we do not show any information about the collapsed threads in a review:

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/125701/110458422-06c21b00-80cc-11eb-9b90-c3c7c3aa6610.png">

We should start the thread fold one line below so it would look like:

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/125701/110458707-5dc7f000-80cc-11eb-80dd-e4231f2e4dc8.png">

Also, perhaps adding some kind of indicator if the thread was recently updated. But was is "recently"?

**Comment by weilbith** [comment]
Very good idea! :+1: 

> Also, perhaps adding some kind of indicator if the thread was recently updated

The `recently` is always tricky as it is a relative value that requires a value to be relative to, which in turn might require caching, which we would like to avoid if possible. So maybe just simplify it and do it as the WebUI with a `edited` hint and eventually but a date for that? Maybe better: calculate the time diff like `edited 5min ago`.

**Comment by weilbith** [comment]
Okay I see. So your dream of solution would that if you have seen a PR/issue already and then open it another time, all comments are folded, except the new ones (or edited ones) you haven't seen before?
I just checked the API, it does not look like their is such data of "comment seen" available. This would leave the burden to store/maintain such data on our own. Which is kind of a night mare or in fact a huge new feature addition. At least architecture and security/stability wise.

**Comment by weilbith** [comment]
As it appears like solving your usability issue could become quite complicated: do you think the possible notifications source we were discussing would solve this? Subscribed threads have a property of the last visited date and the object in the thread which caused the notification.

**Comment by weilbith** [comment]
Just as a note: from my experience this problem is not really better/solved in the WebUI as well. So if I return to a PR where someone responded in a review comment thread I have to search for it. Especially comments in a closed conversation (often just because it were the final words and then got closed) are a nightmare as you have to go through all closed threads and re-check them.
So I'm actually not too optimistic we will find a optimal solution here. Except the detailed caching.

**Comment by weilbith** [comment]
So for the caching approach I would keep it simple and maintain a cache with a mapping of the repo + issue/PR id combined as keys and a date as value. The value represents "last-seen"/"last-opened". When we open a issue buffer we can load this cache data and close all folds of comments/objects have an older created/edited date as this one and keep all other open.

**Comment by pwntester** [comment]
hmm, I think the quickfix for threads sorting them by the date of the last edit of any of its comments should be enough. For example, the thread with that comment which closes it, should appear first in the qf window. Do you see any downsides for this approach?

**Comment by weilbith** [comment]
Oh. Think I got you wrong. You just mentioned the quickfix window. I though you were talking about the regular issue/PR buffer. :speak_no_evil:

**Comment by pwntester** [comment]
Yep, I think that tackling this problem in the PR buffer is very complex. Fortunately, `Octo review threads` give us a nice way to separate threads, provide more context and sort them as we would like
