### ISSUE TITLE
Bugfix - rename octo_isse filetype to allow user filtype plugins

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#126]
Discovered in the PR below. 

>    But I guess it is worth to keep this as a feature. Is there already a mapping for Octo comment edit? Like ce?
 No, but it should be. I will add it
 
 Which reminds me that it is quite hard to add custom mappings. For the issue/PR buffer there is a special filetype and the user can define an `after/ftplugin/...` for it. Wait a sec. This reminds me that the filetype is `octo_issue`. The `ftplugin` syntax for Vim works like that it searches for `ftplugin/{filetype}_*.vim` (and in the `after/ftplugin/{filetype}_*.vim`). So you can have multiple files for the same filetype and postfix them with like `java_mappings.vim` and `java_options.vim`. Or you can define a directory like `ftplugin/{filetype}/*.vim`. But with `octo_issue` this does not work. I had this issue already once back then with another plugin. We want to fix that I think.

_Originally posted by @weilbith in https://github.com/pwntester/octo.nvim/issues/120#issuecomment-793726130_

**Comment by weilbith** [comment]
Hmm. I don't think this makes too much sense. Because there is not easy/good approach to have custom configurations for a buffer based on the buffer name. So I would like to have a mapping on the PR buffer to start a review or see its commits. This would make no sense to have this on a comment for example.
Filetypes can inherit from each other (or was it only syntaxes). So we should be able to have a basic filetype and then have specialized once which inherit from the basic one. This should provide the best of all options I think. Pretty much similar to the highlight group hierarchy we introduced in my PR.
Let me do a quick research after work if this is possible.

**Comment by weilbith** [comment]
Okay so yes, I was not wrong you can do it. It is not really like natural inheritance, but it is a common (?) concept. Checkout the default [markdown](https://github.com/neovim/neovim/blob/7c204af87aa74120a70db14b87c5e7c7096ae478/runtime/ftplugin/markdown.vim#L10) `ftplugin` which "sources" the HTML filetype. We could use the same approach. Then we could also outsource all the buffer options, mappings etc pp which is atm in the Lua logic and just clutters the code. I mean as long as it is something static that does not depend on the specific issue or similar. And mappings should always work. The user can then use the `after/ftplugin/` directory to extend these settings on his behalf.

**Comment by weilbith** [comment]
Could I eventually do this? :grimacing:

**Comment by pwntester** [comment]
Sure!

**Comment by pwntester** [comment]
As part of #137 I removed `octo_reviewthread` filetype and made `octo_issue` unnecessary. All the places were we need to check if we are in an Octo buffer, we now check the buffer name instead. With that, we can keep a octo specific filetype (eg: `octo`) or just use `markdown` as the buffers are now pure markdown buffers (everything that is not markdown such as headers, diff hunk, etc is virtual text and not affected by filetype or syntax). Do you think we should use `markdown`` or `octo`? The later would allow users to apply specific settings to octo buffers which may not be required in markdown ones 🤔

**Comment by weilbith** [comment]
Sorry. I was once working on this "feature". But it quickly escalated and I have thrown it away. I think this improvements needs need to be tackled with more time and then many small steps. It is kinda hard to refactor as no tests do back you up so you know you did not harm any feature/behavior/...  This just a status update. 😬 

Hmm I'm not 100% sure about your question. But generally I think a custom type that inherits and extends Markdown would be the preferable solution. Or does that not work? 🤔

**Comment by pwntester** [comment]
Im aware of syntaxes extending other syntaxes. Is this also possible with filetypes?

**Comment by weilbith** [comment]
Well it basically works 100% the same. You just use `runtime! ftplugin/markdown.vim ftplugin/markdown_*.vim ftplugin/markdown/*.vim`
This is how they do it in the `/usr/share/nvim/runtime` sources.
