### ISSUE TITLE
Feature request - get all reviewers of a PR, requested or not

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#127]
> For some yet unknown reason the API always states that there are no reviewers for any PR. 

The API is actually returning the __requested reviewers__, that is the users that the PR author has requested a review from.
These are the ones that in the WebUI appear with a yellow dot.

If we want to have something similar to what the WebUI shows, then we need to retrieve `pullRequestReviews.author.login` and `pullRequestReview.state`. Also, since I user can leave multiple reviews, we need to "merge" them, so we only show the "strongest" one (eg: if a user leaves `CHANGES_REQUESTED` and `COMMENTED`, only `CHANGES_REQUESTED`). I think that is what the WebUI does, but thats probably work for a new PR

_Originally posted by @pwntester in https://github.com/pwntester/octo.nvim/issues/121#issuecomment-793666563_

**Comment by pwntester** [comment]
Fixed in #130
