### ISSUE TITLE
About description

### ISSUE THREAD

**Issue by crivotz** [pwntester/octo.nvim#136]
## Issue Description

*feature request*

### Describe what happened (or what feature you want)

There is no 'about' description in the repository page

### Describe what you expected to happen

Find an 'about' description 😄 

### How to reproduce it (as minimally and precisely as possible)

1. open repository and look on the top right

### Anything else we need to know?
It's a very stupid issue but it allows some scripts to popolate in the right way the Readme. Thanks

**Comment by pwntester** [comment]
Added one, any suggestions are welcome!
