### ISSUE TITLE
Jumping between comments of other reviewers

### ISSUE THREAD

**Issue by mateuszaaa** [pwntester/octo.nvim#139]
Scenario:
1. i push PR
2. Bob and Alice left few comments under my PR
3. i want to address all the comments from Alice and Bob  - can i jump between comments that are not resolved somehow?

**Comment by pwntester** [comment]
That's something I wanted to implement, not sure if make it a mapping such as `]k` and `[k` to go to the next comment in the file, or maybe add a new Telescope menu to see all unresolved threads and jump to the right place ... or maybe both :)

**Comment by pwntester** [comment]
I added a `[t` and `]t` to jump to the prev and next threads respectively. Can you please give it a try and check if they solve your problem? Thanks!
