### ISSUE TITLE
Key not found: octo_viewer

### ISSUE THREAD

**Issue by Shatur95** [pwntester/octo.nvim#141]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

If the gh application is not authorized, then the following error will be generated immediately when the application starts:

```
Error executing vim.schedule lua callback: ...pData\Local\nvim\pack\plugins\opt\octo.nvim\lua\octo.lua:1244: Key not found: octo_viewer
```

### Suggestion

It would be nice not to display any error at startup even if `gh` is not logged into an account. But when trying to use `:Octo`, display a clear error that authorization is required.

**Comment by pwntester** [comment]
Thanks for the suggestion, it should be fixed now. Please let me know otherwise
