### ISSUE TITLE
octo/reviews.lua:271: Expected lua string

### ISSUE THREAD

**Issue by aareman** [pwntester/octo.nvim#142]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
starting a review gives
Error executing vim.schedule lua callback: ...aham/.config/nvim/plugged/octo.nvim/lua/octo/reviews.lua:271: Expected lua string

### Describe what you expected to happen
to start the review like normal

### How to reproduce it (as minimally and precisely as possible)

1. `Octo pr list`
2. `Octo pr checkout`
3. `Octo review start`

### Tell us your environment
linux, ubuntu 20
![image](https://user-images.githubusercontent.com/10500823/116910170-30527b00-ac13-11eb-9da5-347a0ece4b19.png)
![image](https://user-images.githubusercontent.com/10500823/116910209-45c7a500-ac13-11eb-8601-486aa14dad5d.png)

**Comment by pwntester** [comment]
Should be fixed by f0be84f
