### ISSUE TITLE
Cannot review PRs from forks

### ISSUE THREAD

**Issue by akinsho** [pwntester/octo.nvim#146]
## Issue Description

Type: **bug report**

### Describe what happened (or what feature you want)
Hi 👋🏾 thanks for your work on this plugin, it's really exciting to see this kind of integration in neovim.

So my issue is, when trying to review a PR that is from a fork of your project using octo it errors returning

![image](https://user-images.githubusercontent.com/22454918/118400508-d19cf080-b659-11eb-87ab-7fb57ca1fa81.png)

It seems to fail because the PR is being submitted from a fork of my project.
The `gh` cli seems to be able to checkout this PR without issue though so I'm not sure what the blocker might be on octo's end.

### Describe what you expected to happen
Much like the `gh` cli I would expect that the PR would be checked out without issue

### How to reproduce it (as minimally and precisely as possible)
Find a project with an open PR from a fork you can try [`flutter-tools.nvim`](https://github.com/akinsho/flutter-tools.nvim)
1. Open the pr using `Octo pr list` and selecting one from a fork
2. Run `Octo pr checkout`
3. Error is reproduced

### Tell us your environment
neovim: nvim nightly (updated last night)
OS: ubuntu 21.04

### Anything else we need to know?
I have the `gh` cli installed and am authenticated using SSH 🤷🏾 
Running the checkout command in the cli directly works

**Comment by pwntester** [comment]
Thanks for filing the issue. Will take a look ASAP. In the meantime, try reviewing the PR without checking it out. The review module should fetch the right branch files

**Comment by akinsho** [comment]
Thanks for the quick fix @pwntester, just as an FYI there was also a typo in the error message that was being printed. `Octo` was being spelt as `Oto` I'm not getting the error anymore but just in case it's a logger somewhere that might have the name misspelled in it

**Comment by pwntester** [comment]
Thanks for the typo report, should be fixed now.
