### ISSUE TITLE
Feature request - mark file as reviewed

### ISSUE THREAD

**Issue by Shatur95** [pwntester/octo.nvim#147]
## Issue Description

Type: *feature request*

### Describe what feature you want

When viewing large PRs, it is often required to mark a file as viewed so as not to get confused. This can be done in the web version and in VSCode. It would be awesome to have the same feature here.

**Comment by pwntester** [comment]
Hi, thanks for the suggestion, I implemented it on https://github.com/pwntester/octo.nvim/pull/148
Can you please give it a try and let me know if it works as you expect?

**Comment by Shatur95** [comment]
@pwntester, tested on your PR, it works, thank you!

A small suggestion. Can we use a plain message on `Octo pr checkout` instead of error?

**Comment by Shatur95** [comment]
Hm... When I use `Octo pr start` again, reviewed files displayed as not reviewed in Octo, but marked as viewed on the website.

**Comment by pwntester** [comment]
I changed the `checkout` output. Not sure why `gh` always write to stderr even if there are no errors

**Comment by Shatur95** [comment]
Thanks!
