### ISSUE TITLE
prompt prefix vs title

### ISSUE THREAD

**Issue by rudotriton** [pwntester/octo.nvim#150]
I noticed that this project uses `prompt_prefix` to describe the context/actions: e.g. `Issue Search> `. What's your opinion on changing them to `prompt_title`s instead? The argument here being that using the titles would be consistent with all the other Telescope's pickers as they change the title instead of the prefix.

**Comment by pwntester** [comment]
I dont have any strong opinions about this. Im open to merge a PR for this :)
