### ISSUE TITLE
E5108: No write since last change (add ! to override)

### ISSUE THREAD

**Issue by yingzhu146** [pwntester/octo.nvim#152]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

start PR with  `Octo review start`

go to right pane ("green" highlighted additions).
Try to add a comment using `<space>ca`

```
E5108: Error executing lua /Users/yingzhu/.vim/plugged/octo.nvim/lua/octo/reviews.lua:490: Vim:E37: No write since last change (add ! to override)
```

After getting this error and trying to scroll the buffer pane with `<C-D>` `<C-U>`, I also get 
```
Error detected while processing CursorHold Autocommands for "octo://*":
E5108: Error executing lua /Users/yingzhu/.vim/plugged/octo.nvim/lua/octo/reviews.lua:366: Vim:E37: No write since last change (add ! to override)
```

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
```
Darwin MacBook-Air-4 20.3.0 Darwin Kernel Version 20.3.0: Mon Dec  7 22:03:58 PST 2020

NVIM v0.5.0-dev+1357-g192f89ea1
Build type: Debug
LuaJIT 2.1.0-beta3
```

**Comment by pwntester** [comment]
Thanks for reporting, I cant reproduce the issue though.
Is this PR in a public repo so I can try to reproduce it with the very same PR?

**Comment by yingzhu146** [comment]
So this is a different (related?) error message, when e.g. trying to review a pytorch PR (my cursor is clearly in a diff hunk but I still get and error)
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/59233975/120677700-fae0bd80-c45c-11eb-920a-fa6bfad12a0e.png">

**Comment by pwntester** [comment]
@yingzhu146 for that last problem, can you please send the same screenshot with line numbers enabled and let me know in what line the cursor is at? Note that the lines that accept comment are highlighted in the lineNR column
