### ISSUE TITLE
Octo pr list fails

### ISSUE THREAD

**Issue by vnzongzna** [pwntester/octo.nvim#153]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
I am using Octo.nvim with github enterprise. When in neovim I do `:Octo pr list` it throws the error
`gh: Could not resolve to a Repository with the name 'sfdc/xxxxxxxx'.`.

While when I do `:!gh pr list` it shows me the list.

### Describe what you expected to happen

Show `pr list`

### How to reproduce it (as minimally and precisely as possible)

1. `Octo pr list` on any github enterprise repository

### Tell us your environment
```
:version                                                                                                                                                                      
NVIM v0.5.0-dev+nightly-271-ga129887c0                                                                                                                                        
Build type: Release                                                                                                                                                           
LuaJIT 2.1.0-beta3                                                                                                                                                            
```

**Comment by pwntester** [comment]
Thanks for reporting. Did you change the value of `github_hostname`?

**Comment by vnzongzna** [comment]
Thank you @pwntester I totally overlooked that parameter assuming it'll pickup from `.config/gh/[config|host].yml`. Now I'm facing another error
```
gh: Field 'viewerViewedState' doesn't exist on type 'PullRequestChangedFile'                                                                                                                    
Field 'isCollapsed' doesn't exist on type 'PullRequestReviewThread'                                                                                                                             
Field 'isOutdated' doesn't exist on type 'PullRequestReviewThread' 
```
As soon as the pop-up opens that shows PR, anyway to debug or provide more info?

**Comment by pwntester** [comment]
Weird, those files do exist in the correspoding GraphQL objects:
- https://docs.github.com/en/graphql/reference/objects#pullrequestchangedfile
- https://docs.github.com/en/graphql/reference/objects#pullrequestreviewthread

My guess is that the enterprise server may not be using the latest version an don't have them implemented.

Will try to get access to a GHES and see if its a problem with GHES latest version

**Comment by vnzongzna** [comment]
That might be the reason, currently it's `2.xx` by latest you mean 3.xx?

**Comment by pwntester** [comment]
Yep, I think latest version is 3.1

**Comment by vnzongzna** [comment]
Closing this issue since it's unrelated to Octo but more to APIs supported by older GHES

**Comment by rbhanot4739** [comment]
@pwntester I am having same issue as the OP, where doing `Octo pr list` fails with ` Octo.nvim gh: Could not resolve to a Repository with the name 'org_name/repo_name'`. This is the output of `git remote -v`

```
origin  ssh://org-127256988@github.com/org_name/repo_name (fetch)
origin  ssh://org-127256988@github.com/org_name/repo_name (push)
```

Not sure if I have to set the `github_hostname`.
