### ISSUE TITLE
Support `gh repo` commands

### ISSUE THREAD

**Issue by macintacos** [pwntester/octo.nvim#154]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

Essentially, `:Octo repo <blah>` support. In particular, I'd really like the `list`, `clone`, and `view` commands to be executed by Octo (especially `list`, which I imagine would need the most work to fit into Octo's current model, the others are just executing the relevant `gh` commands). Along the same lines, it'd be nice if you could just provide `:Octo org/repo` or `:Octo <repo_url>` to open the given repo in the browser.

**Comment by pwntester** [comment]
Thanks for the suggestion. I will work on the `Octo repo list` for now but Im not sure what should be done if one of the repos is selected, show the README.md?

The `list` command will be implemented as a telescope menu and then I think the best approach would be to implement `clone` or `open in a browser` as actions that can be triggered from the menu.

as for:

> Along the same lines, it'd be nice if you could just provide :Octo org/repo or :Octo <repo_url> to open the given repo in the browser.

Currently `Octo <issue_pr_url` opens the issue in neovim and from there you can do `Octo issue|pr browser`. I think that treating repo URLs differently (directly go to the browser) my be confusing. So maybe the best approach would be to create a new buffer type that represents the repo (basically the README + some repo details at the top) and the enable `Octo repo browser` and `Octo repo clone`.

> just provide :Octo org/repo

For consistency this should be implemtend as `Octo repo view org/repo`

**Comment by macintacos** [comment]
Sounds good to me!

**Comment by pwntester** [comment]
I implemented a first version on https://github.com/pwntester/octo.nvim/pull/155 Can you please take a look and let me know if you would add any additional to the repo buffer or if you have any other feedback?
