### ISSUE TITLE
[WIP] Improve PR workflow

### ISSUE THREAD

**Issue by pwntester** [pwntester/octo.nvim#16]
- [x] show additions and deletion counts
- [x] list of commits
- [x] list of changed files
- [x] diff
    - e.g. `gh api -H "Accept: application/vnd.github.v3.diff" repos/pwntester/octo.nvim/pulls/3`
- [ ] list reviews
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#list-reviews-for-a-pull-request
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#list-comments-for-a-pull-request-review
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#get-a-review-for-a-pull-request
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#update-a-review-for-a-pull-request
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#submit-a-review-for-a-pull-request
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#dismiss-a-review-for-a-pull-request
- [ ] show review comments if `review_comments` > 0 (only general ones not tied to a specific file)
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#list-review-comments-on-a-pull-request
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#get-a-review-comment-for-a-pull-request
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#update-a-review-comment-for-a-pull-request
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#delete-a-review-comment-for-a-pull-request
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#create-a-reply-for-a-review-comment
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#create-a-review-comment-for-a-pull-request
- [x] add merge action
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#merge-a-pull-request
- [ ] add action to create review
  - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#create-a-review-for-a-pull-request
- [ ] request reviewers
    - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#request-reviewers-for-a-pull-request
    - https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls#remove-requested-reviewers-from-a-pull-request

**Comment by PatOConnor43** [comment]
Hey this is a really cool project. Do you have a suggestion on where I could get started on helping? I started looking at listing commits in the PR view late last night but it looks like you already got that merged :laughing: Anywhere I could help out that isn't in your way?

**Comment by pwntester** [comment]
Im sorry, I should have removed the "help wanted" label since I was already working on it.

Thanks for the help offer, It would be great if you could help with #

Also, feel free to participate in the "review comments" discussion where we are designing how the PR review process is going to look like

**Comment by PatOConnor43** [comment]
Sick, I can take a look at that today. I'll take a look at the discussion as well. Thanks!

**Comment by pwntester** [comment]
No description provided.
