### ISSUE TITLE
[Feature request] Global Telescope menu

### ISSUE THREAD

**Issue by FollieHiyuki** [pwntester/octo.nvim#163]
## Issue Description

Type: *feature request*

### Describe

First, thanks for an amazing plugins. Don't know whether it was asked before, but here is my proposal.

I want octo.nvim to have a global Telescope menu (either bound to `:Octo` or `:Octo commands`), from which users can access other commands. This will make key bindings for Octo easier (literally just need 1 for all functionalities).

The results window will prompt for `repo card review ... issue`, then next after choosing `issue` it will prompt for `list create ... reopen` (much like the current command auto-suggestion, but with Telescope interface). The preview window can describe what the currently selected command does, for example.

**Comment by pwntester** [comment]
Thanks for the suggestion, looks like something cool and easy to implement

**Comment by tami5** [comment]
I guess I can work on that since it solves my issue as well. opening a pr soon
