### ISSUE TITLE
Cannot find repo when unspecified

### ISSUE THREAD

**Issue by maisiliym** [pwntester/octo.nvim#17]

**Comment by maisiliym** [comment]
`gh` lost Li's message again.
The problem seems to be with `get_remote_name`

**Comment by pwntester** [comment]
What do you mean that your message was lost?

**Comment by maisiliym** [comment]
Sorry, that was ambiguous. The description was empty from a bad `gh` setup, which is unrelated to the issue at hand.
The issue is, as the title says; the repo name cannot be infered from `pwd`.
`:Octo issue list`
`> Cannot find repo`
Hence the comment about `get_remote_name`
Perhaps it would be more appropriate to use `string.find` to parse the cwd

**Comment by pwntester** [comment]
No description provided.
