### ISSUE TITLE
How to go to file from PR comment (PR buffer)

### ISSUE THREAD

**Issue by entropitor** [pwntester/octo.nvim#173]
When you do `Octo pr edit [number]` you get a PR buffer which can contain comments on files, how do you go from the comment to a file. 

I cannot put my cursor on the filename to use `gf` to go to the file. I tried enter and read the README but couldn't find anything

**Comment by pwntester** [comment]
Hi @entropitor 

Do you mean something like:

<img width="412" alt="imagen" src="https://user-images.githubusercontent.com/125701/126005734-92be78a2-a708-45c3-a3af-b69245177720.png">

If so, I can make `gf` work if the file is found in the CWD

**Comment by entropitor** [comment]
Yes, exactly! It would be really nice to open up your own PR and see the review comments and have an easy shortcut to go to the file at the exact location of the comment.

**Comment by pwntester** [comment]
Implemented in https://github.com/pwntester/octo.nvim/pull/179 
@entropitor, can you please test it?

**Comment by entropitor** [comment]
I want to test it but since recently I keep getting (on the master branch):

> [Octo] You are not logged into any GitHub hosts. Run `gh auth login` to authenticate.

even after logging in.

Running `gh pr list` works just fine, even from vim

**Comment by entropitor** [comment]
https://github.com/pwntester/octo.nvim/issues/173#issuecomment-882366113 seems to be due to g:octo_viewer not being set

The PR seems to work well 👍 

If we want to be fully consistent with vim `gf` should open file and `gF` should be file + line number, but for me this works

**Comment by pwntester** [comment]
> #173 (comment) seems to be due to g:octo_viewer not being set

I have experience that recently too. I have changed the way we get the `octo_viewer` so instead that asynchronously fetching it on octo start, which can lead to a race condition where you enter an Octo command before the `octo_viewer` var is ready, I fetch it synchronously on the first `gh.run` execution.

> If we want to be fully consistent with vim gf should open file and gF should be file + line number, but for me this works

I will leave it as is for now, after all `gf` is just the mapping and users may change it to something else so it doesn't need to be 100% consistent with vim :)
