### ISSUE TITLE
Error about FoldToggle in the command line

### ISSUE THREAD

**Issue by lalitmee** [pwntester/octo.nvim#185]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

When I am opening the `Octo pr list` and as soon as content appears in the preview, it shows an error in the command line

![image](https://user-images.githubusercontent.com/10762218/127762619-57d7de86-8e62-4658-b087-92be823c6674.png)

### Describe what you expected to happen

I want to know why that error is coming and don't want it to occur.

### How to reproduce it (as minimally and precisely as possible)

1. run `Octo pr list`
2. wait for the preview of the PR to come
3. you will see this error

### Tell us your environment

- **OS:** PopOs (Ubuntu 20.04)
- **neovim**
```
NVIM v0.6.0-dev+81-gc642f3ac2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/lalitmee/data/Github/neovim/build/config -I/home/lalitmee/data/Github/neovim/src -I/home/lalitmee/data/Github/neovim/.deps/usr/include -I/usr/include -I/home/lalitmee/data/Github/neovim/build/src/nvim/auto -I/home/lalitmee/data/Github/neovim/build/include
Compiled by lalitmee@pop-os

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

### Anything else we need to know?

Nothing

**Comment by pwntester** [comment]
Hi, thanks for the report

This seems to be caused by a plugin. Which plugin is bringing the `FoldToggle` command? is it `vim-markdown-folding`? do you have any autocommands running it on markdown buffers?

**Comment by lalitmee** [comment]
@pwntester, oh yeah. Actually this `FoldToggle` command I was declaring in the `ftplugin` for `markdown`. Got it.
