### ISSUE TITLE
Error while using the provided mappings from Octo

### ISSUE THREAD

**Issue by ShadowItaly** [pwntester/octo.nvim#186]
## Error when using the README provided mappings for closing an issue

Type: *bug report*

### Lua shows an error message
The error message
```
E5108: Error executing lua /root/.vim/plugged/octo.nvim/lua/octo/mappings.lua:15: attempt to call field 'change_issue_state' (a nil value)
```

### How to reproduce it (as minimally and precisely as possible)

1. Use the master branch of Octo
2. Use the provided keymappings in the README
3. Enter an issue an type <space>ic to Close the issue

**Comment by pwntester** [comment]
Thanks for reporting and fixing the issue
