### ISSUE TITLE
How to do searches for PRs based on GitHub attributes?

### ISSUE THREAD

**Issue by kamilc** [pwntester/octo.nvim#203]
I'm having a hard time figuring out the `:Octo pr list (...)` command arguments that would correspond with:

```
gh pr list --search "is:open is:pr review-requested:@me"
```

Is what's above possible in octo? Thnks!

**Comment by skbolton** [comment]
Came here to ask the same thing. I am not able to get your suggestion to work though. I have tried both `:Octo pr search review-requested:@me` and doing `:Octo pr search` and then typing `review-requested:@me` into the telescope prompt. What am I doing wrong?

**Comment by skbolton** [comment]
Apologies, I found the example in the FAQ
