### ISSUE TITLE
[ Feature Request ] support fzf-lua

### ISSUE THREAD

**Issue by ldelossa** [pwntester/octo.nvim#206]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
I have a very heavy fzf-lua workflow. I'd like to try `octo.nvim` but I'd rather not  depend on telescope since I already use another fuzzy searcher. 

### Describe what you expected to happen
Create support for fzf-lua: https://github.com/ibhagwan/fzf-lua as well as telescope. I think this is a safe beat since a lot of people love fzf.

**Comment by jin-ahn** [comment]
Same here, Would love to use fzf instead of telescope!

**Comment by pythops** [comment]
Any progress on that one ? :pray:

**Comment by pwntester** [comment]
No sorry, once decoupled, Im happy to receive PRs for other fuzzy providers but Im not planning on implementing this myself

**Comment by mhanberg** [comment]
I recently switched to fzf-lua from fzf.vim and am going to work octo into my workflow, so I'll chip away at this as I get time.
