### ISSUE TITLE
Error trying to assign a user to an issue

### ISSUE THREAD

**Issue by waltermaldonado** [pwntester/octo.nvim#221]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)
Three problems:
1. When I hit space-aa the telescope window appears with the corners not showing (font: Meslo LGS NF)
2. When I start typing I get an indicator `1/1` but no option to select
3. If I hit enter an exception is raised on the close method call of the picker
```
E5108: Error executing lua ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:251: Vim(lua):E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1300: attempt to index field 'finder' (a function
value)
stack traceback:
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:1300: in function 'on_close_prompt'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_win_close'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:251: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function '_close'
        .../start/octo.nvim/lua/octo/pickers/telescope/provider.lua:859: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'nvim_win_close'
        ...cker/start/telescope.nvim/lua/telescope/actions/init.lua:251: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function '_close'
        .../start/octo.nvim/lua/octo/pickers/telescope/provider.lua:859: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
```

### Describe what you expected to happen
I should be able to self-assign an issue, or assign other people

### How to reproduce it (as minimally and precisely as possible)

1. :Octo issue list
2. Select an issue
3. space-aa
4. Type in a name and hit enter

### Tell us your environment
- MacOS BigSur 11.3.1
- NVIM v0.6.0-dev+650-g04c7b5503
- Octo at commit 44df9c0486ec875a0e104d5fe70a31d1a33bf4f7
- Telescope at commit [telescope.nvim#ef245548a858690fa8f2db1f1a0eaf41b93a6ef6](https://github.com/nvim-telescope/telescope.nvim/commit/ef245548a858690fa8f2db1f1a0eaf41b93a6ef6)
- gh installed with brew

### Anything else we need to know?
No.

**Comment by pwntester** [comment]
Thanks for reporting the issue. Seems like Telescope APIs has changes a bit. Can you please try #222 and see if it fixes for you?
