### ISSUE TITLE
Error while reading issue.

### ISSUE THREAD

**Issue by zalegrala** [pwntester/octo.nvim#237]
## Issue Description

Periodically when using Octo, I see the following error. In particular, reloading an issue.

Type: *bug report*

```
Error executing vim.schedule lua callback: Vim:E474: Attempt to decode a blank string                                                              
stack traceback:                                                                                                                                   
        [C]: in function 'json_decode'                                                                                                             
        ...ck/packer/start/octo.nvim/lua/octo/model/octo-buffer.lua:284: in function 'cb'                                                          
        ...unarvim/site/pack/packer/start/octo.nvim/lua/octo/gh.lua:83: in function 'cb'                                                           
        vim.lua:285: in function <vim.lua:285> 
```

### Describe what happened (or what feature you want)

It isn't clear what this impacts since the issue does seem to load, but...

### Describe what you expected to happen

...I wouldn't expect to see an error here.

### How to reproduce it (as minimally and precisely as possible)

1. Open an issue.
2. Wait approx 200ms 
3. Error

### Tell us your environment

❯ uname -a
Linux flappy 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux

### Anything else we need to know?

Very new to Octo.

**Comment by pwntester** [comment]
It seems like GH is sending an unexpected response for the `contributors` api endpoint. This is not the case for any of the repos I use. Can you share a repository/issue where this issue happens?

**Comment by zalegrala** [comment]
I don't believe I'm in a repo when I execute this.  Perhaps where this comes from.

**Comment by zalegrala** [comment]
Yep, not in a repo when I see this come up.  I've got a project I'm a part of that only has issues, no code, just as a means of tracking work, etc.

**Comment by pwntester** [comment]
Thanks, I was able to reproduce the issue on that kind of repos. Should be fixed now

**Comment by zalegrala** [comment]
Excellent, thank you.
