### ISSUE TITLE
Nil comment_ranges

### ISSUE THREAD

**Issue by c0ppelius** [pwntester/octo.nvim#252]
## Issue Description

Bug report

### Describe what happened (or what feature you want)

Attempting to comment at a line using results in a bad argument to `ipairs` 
```lua
  for i, range in ipairs(comment_ranges) do
```
[here](https://github.com/pwntester/octo.nvim/blob/33224362e20e1b3e87eb7ef2d669de6c60e727db/lua/octo/reviews.lua#L459) because comment_ranges is empty. 

### Describe what you expected to happen

What is described in the documentation. 

### How to reproduce it (as minimally and precisely as possible)

1. Check out PR either by cloning repo locally and calling `Octo pr list` or including the URL of the repo in the call. 
2. `Octo review start`
3. `<space>ca` on some line. 

### Tell us your environment

Both on MacOS Monterey with nvim 0.61 and Ubuntu 20.04 with nvim 0.7

### Anything else we need to know?

This looks like a nice plug in. Thanks for making it.

**Comment by pwntester** [comment]
Thanks for reporting the issue. is the repo/pr causing this error public so I can try to reproduce it?
Also, are you trying to place a comment on a file that has been renamed/moved?

**Comment by c0ppelius** [comment]
Unfortunately, it is not public :/ 

It was not rename/moved. It was a totally new file added in the PR.

**Comment by pwntester** [comment]
Thanks for the pointer, can you try again and see if latest commit fixes the issues?

**Comment by c0ppelius** [comment]
Still getting the same error: 
```
E5108: Error executing lua ...im/site/pack/packer/start/octo.nvim/lua/octo/reviews.lua:459: bad argument #1 to 'ipairs' (table expected, got nil)     
stack traceback:                                                                                                                                      
        [C]: in function 'ipairs'                                                                                                                     
        ...im/site/pack/packer/start/octo.nvim/lua/octo/reviews.lua:459: in function 'add_review_comment'                                             
        [string ":lua"]:1: in main chunk 

```
I’ve added you as an outside collaborator to the repository for further testing.

**Comment by pwntester** [comment]
Thanks for sharing the repo. It should be fixed now, please let me know if it works for you now

**Comment by c0ppelius** [comment]
Unfortunately, I have still have the same error.

**Comment by pwntester** [comment]
Just to double check, are you using the PR branch?

**Comment by c0ppelius** [comment]
🤦‍♂️ It is all good now. 

Thanks for your patience and for the great plugin!
