### ISSUE TITLE
How to list all issues assigned to me in all repos?

### ISSUE THREAD

**Issue by zalegrala** [pwntester/octo.nvim#257]
## How to list all issues assigned to me in all repos?

Type: question
### Describe what happened (or what feature you want)

I've got a pile of issues assigned to me across a few projects, and it would be handy to be able to open any of them regardless of my working directory.

### Describe what you expected to happen

`:Octo issue list assigneee:zalegrala` would list all issues assigned to me.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

Linux, neovim v0.6.1

### Anything else we need to know?

Still learning to use this plugin, but so far has been pretty great.  Thanks for the efforts.

**Comment by pwntester** [comment]
Looks like a nice feature to have, will take a look 👀

**Comment by pwntester** [comment]
You can now try: `lua require("octo.pickers.telescope.provider").picker.search_issues({prompt = "assignee:zalegrala", static = true})`. Still not sure about the final command to bind this to since `Octo issue list` will try to look the CWD for a github repo and use it for the search. Some options:
- `Octo search <prompt>` where you would need to add `is:issue` or `is:pr` as part of the prompt
- `Octo search issue <prompt>`
- `Octo issues <prompt>`
I think I prefer the first one. Thoughts?

**Comment by zalegrala** [comment]
Oh awesome, thank you for this change.  I like the first one also since as you mention, `is:pr` is also handy for going to PRs that are open, etc.  Users can bind that to a key easy enough for shortcuts to PRs or Issues.  Though I do notice that the current `picker.search_issuse` doesn't seem to return results for PRs when `is:pr` is in the query string.  I'll be using this quite a bit.

**Comment by pwntester** [comment]
Alright, I just implemented this. You should be able to do `:Octo search assigneee:zalegrala is:pr` now. Let me know if it works for you

**Comment by zalegrala** [comment]
I've updated the plugin, and it looks to work great.  Small thing to note if you go to document this, is that the label for a PR is `author:` where on an issue it seems to be `assignee:`.  But just testing around, it seems like we can use whatever search criteria in `:Octo search` is that correct?

**Comment by zalegrala** [comment]
Oh I guess assignee on PR is also valid.

**Comment by pwntester** [comment]
Thanks!
