### ISSUE TITLE
When review PR, diff view is not appear and `attempt to get length of field 'left_lines' (a nil value)` error occur

### ISSUE THREAD

**Issue by younuk23** [pwntester/octo.nvim#262]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
- when i open PR and review changes, sometimes the diff window does not open, and only loading view is opening(file view window location is octo/null)
- then, when i choose a file in file list, there is error
```
E5108: Error executing lua ...e/nvim/plugged/octo.nvim/lua/octo/reviews/file-entry.lua:201: attempt to get length of field 'left_lines' (a nil value)
stack traceback:
        ...e/nvim/plugged/octo.nvim/lua/octo/reviews/file-entry.lua:201: in function 'load_buffers'
        ...share/nvim/plugged/octo.nvim/lua/octo/reviews/layout.lua:146: in function 'set_file'
        ...local/share/nvim/plugged/octo.nvim/lua/octo/mappings.lua:159: in function <...local/share/nvim/plugged/octo.nvim/lua/octo/mappings.lua:154>
        ...local/share/nvim/plugged/octo.nvim/lua/octo/mappings.lua:9: in function 'on_keypress'
        [string ":lua"]:1: in main chunk

```
![image](https://user-images.githubusercontent.com/54208214/154192470-8b679cb3-3e0d-487f-a3ec-020a00ad3001.png)

### How to reproduce it (as minimally and precisely as possible)

1. `:Octo PR list` in project folder
2. `Octo review start` in PR

### Tell us your environment
- nvim v0.6.1
- use 'vim-plug' for plugin manager
here is my plugin list
```
    Plug 'dracula/vim', { 'as': 'dracula' }
    Plug 'tomasr/molokai' "color scheme
    Plug 'leafgarland/typescript-vim' " TypeScript syntax
    Plug 'jparise/vim-graphql'        " GraphQL syntax
    Plug 'pangloss/vim-javascript' "javascript support
    Plug 'maxmellon/vim-jsx-pretty'   " JS and JSX syntax
    Plug 'styled-components/vim-styled-components', { 'branch': 'main' } "Styled-components Syntax
    Plug 'neoclide/coc.nvim', {'branch': 'release'} "Intelignece
    Plug 'vim-airline/vim-airline' "StatusBar
    Plug 'vim-airline/vim-airline-themes' "StatusBar
    Plug 'tpope/vim-fugitive' "Syntatic Sugar With Git 
    Plug 'airblade/vim-gitgutter' "Git Column
    Plug 'preservim/nerdtree' "File Explorer
    Plug 'Xuyuanp/nerdtree-git-plugin' "Nerd Tree git diagnostic
    Plug 'ryanoasis/vim-devicons' "NerdTree Icon Theme
    Plug 'tiagofumo/vim-nerdtree-syntax-highlight' "NerdTree Highlight
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } } "Fuzzy Finder
    Plug 'junegunn/fzf.vim' "Fuzzy Finder
    Plug 'stsewd/fzf-checkout.vim'
    Plug 'tpope/vim-surround' "Add Surround Operator
    Plug 'tpope/vim-repeat' "Advanced Dot operator
    Plug 'tpope/vim-commentary' "Comment Easy
    Plug 'alvan/vim-closetag' "Auto Close Tag
    Plug 'AndrewRadev/tagalong.vim' "Change Tag Name both start and end"
    Plug 'tpope/vim-eunuch' "UNIX Shell Commands Syntatic Sugar
    Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app && yarn install'  }
    Plug 'johngrib/vim-f-hangul'
    Plug 'rust-lang/rust.vim'
    Plug 'easymotion/vim-easymotion'
    Plug 'mattn/emmet-vim'
    Plug 'tamago324/vim-browsersync'
    Plug 'tyru/open-browser.vim'
    Plug 'kassio/neoterm'
    Plug 'Yggdroot/indentLine'
    Plug 'szw/vim-maximizer'
    Plug 'junegunn/vim-easy-align'
    Plug 'vim-test/vim-test'
    Plug 'nvim-lua/plenary.nvim'
    Plug 'nvim-telescope/telescope.nvim'
    Plug 'kyazdani42/nvim-web-devicons'
    Plug 'pwntester/octo.nvim'

```

### Anything else we need to know?
- when i open first pr and review them, it works well usually but, when i open second pr and review them, the above error occur
- when error is occured, I close the vim and reopen and try again, it works well

**Comment by pwntester** [comment]
Hi, thanks for reporting this! I was not able to reproduce it on PRs with small number of changed files (8). However, I got this error when trying a PR with many files (70). Was this also your case?

In my case, it seems like I get `Post "https://api.github.com/graphql": net/http: TLS handshake timeout` for many of the file requests.

Will try to figure out why Im getting this error

**Comment by pwntester** [comment]
@ younuk23 can you please check if latest version fixes the issue?

**Comment by taraslis453** [comment]
I am still getting this issue

**Comment by dlacaille** [comment]
I am having this issue as well, on nvim 0.6.1 running on a Mac. I am using Lunarvim but tried with NvChad as well, same error. The error also occurs on all of my projects. I simply can't jump forwards or backwards using [q or ]q.

**Comment by dlacaille** [comment]
@pwntester unfortunately I am now knowledgable enough to fix the issue but I can reproduce on my machine. Is there anything you might need to reproduce? Here is what might work:

1. Install nvim 0.6.1
2. Install LunarVim
3. Add the following to config.lua

```lua
lvim.plugins = {
    {"pwntester/octo.nvim", config = function() require"octo".setup() end}
}
```

If the issue is still not happening for you, I can try reproducing it on a docker container.

**Comment by pwntester** [comment]
@dlacaille this seems to be a different issue with the `]q`, `[q` mappings. Please check if a2793a4c1814d27168686730cf2576915f9f556f fixes it for you

**Comment by dlacaille** [comment]
@pwntester the issue is still happening after updating:

![image](https://user-images.githubusercontent.com/6683854/163512888-4572d37a-061d-421a-a823-eaea5fb559fa.png)

**Comment by pwntester** [comment]
@dlacaille the stack trace seems to indicate that you are not using the latest version. Can you verify you are on the latest commit?

**Comment by taraslis453** [comment]
Fixed for me 👍

**Comment by dlacaille** [comment]
I tried again this morning and it seems to be working! Thank you :)
