### ISSUE TITLE
Filter assignee list and/or pass pass username to "assignee add"

### ISSUE THREAD

**Issue by NathanKleekamp** [pwntester/octo.nvim#267]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

First off, I absolutely adore this plugin. It's first rate!

I'd love the ability to pass a username to `Octo assignee add` instead of popping open a pick list that filters while typing. Something like:

```
:Octo assignee add JimmyCrackedCorn
```

The filter while typing functionality can be slow because it seems to search the entirety of Github's user base. Might be also be useful to limit the assignees to repo members (if a private repo).

**Comment by pwntester** [comment]
Thanks for the suggestion, I have added support for passing a login to the `assignee` and `reviewer` commands. Will add it as well for labels
