### ISSUE TITLE
`Octo issue create` creates the issue before saving the buffer or providing body

### ISSUE THREAD

**Issue by muniter** [pwntester/octo.nvim#272]
### Describe what happened (or what feature you want)

When using `Octo issue create` the issue is immediately created with the provided title, not waiting to get a body/description before.

### Describe what you expected to happen

When creating an issue, ask me for the title, then take me to the buffer where I'll edit the body. Once the buffer is saved the issue is created.

This is problematic because it notifies the repo watchers while you haven't completed the issue. It might even get closed by the repo maintainers or a bot.

### How to reproduce it (as minimally and precisely as possible)

1. `Octo issue create`
2. provide a title
3. go to the repository you'll se an issue with empty body and the provided title

### Tell us your environment

Neovim HEAD

### Anything else we need to know?

**Comment by pwntester** [comment]
This is something I wanted to implement, havent found the time yet. But is in my TODO list

**Comment by pwntester** [comment]
I have implemented this as part of #294 
When creating an issue, Octo will ask if you want to use the contents of the current buffer as the body of the issue. So you can work on the issue's body and when ready, create the issue from it
