### ISSUE TITLE
[ Feature Request ] squash and merge PR

### ISSUE THREAD

**Issue by mthnglac** [pwntester/octo.nvim#274]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

I want to be able to squash and merge my PR. As far as I realized from source code, right now it is sending only one option to its command function:

```lua
  ...

  merge_pr = function()
    require("octo.commands").merge_pr "commit"
  end,

  ...
```

### Describe what you expected to happen

I'd like to have this mapping when I'm in pull request:
```lua
  ...

  pull_request = {
    squash_and_merge_pr = "<space>psm",
  },

  ...
```

or is there any way to accomplish this operation?

**Comment by pwntester** [comment]
Should be fixed now, please verify
