### ISSUE TITLE
Filtering PRs doesn't work

### ISSUE THREAD

**Issue by taniotanio7** [pwntester/octo.nvim#281]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

I try to filter Pull Requests by their author, however Octo returns the entire PR list for the repo

### Describe what you expected to happen

Return PR list filtered by author like in the GitHub UI or gh CLI tool

<img width="1262" alt="CleanShot 2022-04-11 at 14 50 20@2x" src="https://user-images.githubusercontent.com/4144459/162742927-6a46271e-6553-4131-8330-df2f3c0d77a6.png">

<img width="845" alt="CleanShot 2022-04-11 at 14 50 46@2x" src="https://user-images.githubusercontent.com/4144459/162742959-b00b031a-7ffb-4c26-b2ad-7f6ffa46c0ed.png">

or if the params are invalid an error message

### How to reproduce it (as minimally and precisely as possible)

1. Type `:Octo pr list createdBy=taniotanio7` or `:Octo pr list author=taniotanio7`
2. List is not filtered

https://user-images.githubusercontent.com/4144459/162743692-31fe4e8e-f3bc-42ad-b861-85bd5beb10f7.mp4

### Tell us your environment

macOS

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

gh version 2.7.0 (2022-03-30)

Tested on repo: https://github.com/saleor/saleor-dashboard
Vim configuration: https://github.com/taniotanio7/dotfiles/tree/main/.config/nvim

### Anything else we need to know?

I think the issue might be the GraphQL query - in GitHub docs there is an option to search PRs by author https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-author however it cannot be done when viewing repo - only [`search`](https://docs.github.com/en/graphql/reference/queries#searchresultitemconnection) query accepts params for filtering PRs the [`repository`](https://docs.github.com/en/graphql/reference/queries#repository) query doesn't have this option

**Comment by pwntester** [comment]
Hi @taniotanio7, your guess was right, with `Octo issue list` you can only filter by the keys documented [here](https://docs.github.com/en/graphql/reference/input-objects#issuefilters). These keys include `createdBy` so `:Octo issue list createdBy=taniotanio7` should work, but not for PRs that only accept the [following keys](https://github.com/pwntester/octo.nvim/blob/master/lua/octo/pickers/telescope/provider.lua#L34). 
You can use the `search` command for that. eg: `lua require("octo.pickers.telescope.provider").search({prompt="is:pr author:pwntester repo:github/codeql"})`

**Comment by taniotanio7** [comment]
Great! Thanks :) I totally missed the search command.

I've made this PR to update the README https://github.com/pwntester/octo.nvim/pull/284

**Comment by pwntester** [comment]
Cool, thank!
