### ISSUE TITLE
Toggle completion

### ISSUE THREAD

**Issue by nekowasabi** [pwntester/octo.nvim#287]
## Issue Description

*feature-request*

When I type `#` to add a header line in markdown, it automatically completes the issue number.

I tried to turn off auto-completion and set it up so I can complete manually, but the setting for completion is defined directly in the code.
Therefore, it does not appear that I can change the setting.

https://github.com/pwntester/octo.nvim/blob/490d7145070b6326610d5d41238b1d8e88606f8b/lua/octo/model/octo-buffer.lua#L78-L80v

### Describe what happened (or what feature you want)

When writing markdown, I would appreciate the addition of a setting to toggle completion so that unintended completions are not performed.

### Describe what you expected to happen
1. Set octo's setting like `manual_completion = true` in init.vim
2. Execute `Octo issue edit xxxx`
3. Input `#`
4. Input `<C-x><C-o>` for manual completion
 
### Tell us your environment
nvim v0.7.0
OS: debian

**Comment by pwntester** [comment]
Hi, I think it makes sense to disable the mappings  and document them in the FAQ

**Comment by nekowasabi** [comment]
Thank you @pwntester !! 👍
