### ISSUE TITLE
Reply to comments from pull request view

### ISSUE THREAD

**Issue by axkirillov** [pwntester/octo.nvim#288]
## Issue Description

*feature request*

### Describe what happened (or what feature you want)

It seems that `commend add` only works in the context of a review. As a creator of a PR I want to be able to reply to comments from my reviewers without "starting" a review. Currently if I press `<space>ca` or run `:Octo comment add` in the PR overview tab I get this message

`Start a new review to reply to a thread`

### Describe what you expected to happen

pressing `<space>ca` in pr comment thread should open a comment buffer 

### How to reproduce it (as minimally and precisely as possible)

1. Open a PR from :Octo pr list
2. press `<space>ca` in a comment thread or run `:Octo comment add`
3. see this message  `Start a new review to reply to a thread`

### Tell us your environment
MacOS Monterey 12.3 
Neovim 0.7
octo.nvim latest (installed with vim-plug)

**Comment by pwntester** [comment]
Thanks for reporting, this was figured out by @ldelossa [here](https://www.reddit.com/r/neovim/comments/ul1tx3/introducing_ghnvim_a_fully_featured_github/i7sswbd/). Will try to implement it soon

**Comment by axkirillov** [comment]
@pwntester awesome, thank you 😃

**Comment by pwntester** [comment]
@axkirillov Just implemented this as part of #294 would you mind testing it?

**Comment by pwntester** [comment]
@axkirillov thanks for letting me know, no need to debug though, if you could please send me error messassge or screenshot and I will look into it

**Comment by pwntester** [comment]
Thanks @alex-popov-tech yep, please cursor on `THREAD COMMENT` line or any or the comments on the thread and press `<space>ca` or `:Octo comment add`

**Comment by alex-popov-tech** [comment]
@pwntester it works! but for some reason it duplicates comment, ie i put one comment in buffer, then do `:w` to send it, then i do `Octo pr reload` and then i see 2 same comments :(

**Comment by pwntester** [comment]
@alex-popov-tech thats weird, I cannot reproduce it. Can you please send a video so I can see the exact line where you run the add comment command?
