### ISSUE TITLE
Multiple github accounts can't connect

### ISSUE THREAD

**Issue by tyetyetye** [pwntester/octo.nvim#296]
At work I use my personal github account and one for my organization.

my ~/.ssh/config
```
# Personal GitHub account
Host github.com
HostName github.com
User git
AddKeysToAgent yes
IdentityFile ~/.ssh/id_ed25519

# Work2 GitHub account
Host github.com-work
HostName github.com
User git
AddKeysToAgent yes
IdentityFile ~/.ssh/id_ed25519_work
```

.git/config for a personal repo
```
[remote "origin"]
	url = git@github.com:tyetyetye/dotfiles.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```
.git/config for work related repo
```
[remote "origin"]
  url = git@github.com-work:work/repo.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	gh-resolved = base
```

Is there any way for octo to work for the work related git repos that use git@github.com-work?
I can change it to git@github.com, but then lazygit nvim plugin stops working.

Thank you.

**Comment by pwntester** [comment]
Please try again, user config was not being applied

**Comment by tyetyetye** [comment]
Thanks, it works now.  I really appreciate that!

Initially I tried gh.nvim, but it cannot create issues.  Thanks again :)

**Comment by pwntester** [comment]
> Weird, I thought I replied to this one. My concern was that for correct identification of the aliases, we need to parse the ssh config file which is out of the scope of this plugin. Unless there is a different way Im not familiar with

I replied in https://github.com/pwntester/octo.nvim/issues/295 sorry, I though it was the same issue
