### ISSUE TITLE
Trying to create a PR using `octo create pr [draft]` succeeds partially with error

### ISSUE THREAD

**Issue by shivanthzen** [pwntester/octo.nvim#299]
**BUG**

In a git repo, try 
`:Octo create pr draft`
Navigate the prompts , (bse master, Confirmation etc )
The PR is successfully created but while opening the description window, it fails with the following error

![Error](https://user-images.githubusercontent.com/92778810/172750799-1a8557ea-a213-45f1-a1f0-fb096ee191cf.jpg)

**Describe what you expected to happen**
Able to write and submit PR description

**How to reproduce it (as minimally and precisely as possible)**
Try to create a PR with Octo pr create in an org project
Tell us your environment
MacOS

NVIM v0.8.0-dev+352-g19e80738e
Build type: Release
LuaJIT 2.1.0-beta3

**Anything else we need to know?**
Don't think so!

**Comment by pwntester** [comment]
Hi,

Thanks for reporting the issue, I was not able to reproduce it, but added some null checks to try to prevent the error. Can you please try https://github.com/pwntester/octo.nvim/pull/300 ?

**Comment by shivanthzen** [comment]
Hey, saw the comment now. The latest master works as expected after the merge. Thanks.
