### ISSUE TITLE
Feature - Respect PR template when creating a new PR. 

### ISSUE THREAD

**Issue by shivanthzen** [pwntester/octo.nvim#304]
## Issue Description

Type: *feature request*

### Describe 
When creating a new PR  using octo, repect the Pull request template stored in `.github/PULL_REQUEST_TEMPLATE.md` of the REPO . Currently Octo creates a PR with empty descritption. 
### References
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by pwntester** [comment]
Thanks for filing an issue, this is something I wanted to do but didnt get the time to tackle it yet.

Seems like the templates are available via the GraphQL API:

- Repository.issueTemplates: [[IssueTemplate](https://docs.github.com/en/graphql/reference/objects#issuetemplate)] (title, name, body, about)
- Repository.pullRequestTemplates: [[PulRequestTemplate](https://docs.github.com/en/graphql/reference/objects#pullrequesttemplate)] (body, filename)

**Comment by augustocdias** [comment]
Would be nice to also have the possibility to open the PR as a draft.

**Comment by shivanthzen** [comment]
You can already do it with `Octo pr create draft`

**Comment by shivanthzen** [comment]
To the original question,  looks like *gh cli* already supports choosing template when I do `gh pr create`. Its just a matter of letting piping the ourput to a select window ?

**Comment by augustocdias** [comment]
> ~~To the original question,  looks like *gh cli* already supports choosing template when I do `gh pr create`. Its just a matter of letting piping the ourput to a select window ?~~
> 
> Never mind just realised octo doesn't use gh

No? Then why it is on the dependencies' list?

**Comment by pwntester** [comment]
> No? Then why it is on the dependencies' list?

It uses `gh` to send most of the graphql/rest requests but does not use the `gh` commands directly if that makes sense
So to create a new pr, we use `gh api ...` to send a request to the correct graphql API endpoint, but do not use `gh pr create` command

**Comment by pwntester** [comment]
I started working on this, you can check this PR https://github.com/pwntester/octo.nvim/pull/313 and let me know any bugs/thoughts
