### ISSUE TITLE
BUG: Diff Highlight is lost in PR review when saving a comment

### ISSUE THREAD

**Issue by iabdelkareem** [pwntester/octo.nvim#307]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
When performing PR review, after writing and saving a comment the diff highlights are lost

### Describe what you expected to happen
Diff highlights remain

### How to reproduce it (as minimally and precisely as possible)

1. Start a review "Octo review start/resume"
2. Add a comment (default <space>ca)
3. Write something and save the buffer
4. Switch to the diff window

### Tell us your environment
Nvim v0.7.2
Fedora 37

### Anything else we need to know?
No

**Comment by pwntester** [comment]
Thanks for reporting the issue @iabdelkareem can you please check if latest commit fixes it?

**Comment by iabdelkareem** [comment]
Thank you for your responsiveness it works perfectly now ^^ @pwntester
