### ISSUE TITLE
[BUG] `:Octo repo list` fails

### ISSUE THREAD

**Issue by colin-heffernan** [pwntester/octo.nvim#332]
## Issue Description
`:Octo repo list` fails. Whenever I type the command, I get the follorwing error:
`[telescope] [WARN 22:09:10] ..mPackages/start/telescope-nvim/lua/te...try_maker.lua:401: bad argument #1 to 'sub' (string expected, got nil)`

Type: *bug report*

### Describe what happened (or what feature you want)
The previous error occurs and the telescope list is empty.

### Describe what you expected to happen
The telescope prompt should list all of my repos.

### How to reproduce it (as minimally and precisely as possible)

1. Run `:Octo repo list`

### Tell us your environment
NixOS Unstable 22.11
Neovim Nightly

### Anything else we need to know?
I'm new to Octo and may misunderstand things. It's taking me some time to figure things out. If this is user error, please don't take it out on me.

**Comment by pwntester** [comment]
Thanks for reporting the issue, it should be fixed now. Please let me know otherwise
