### ISSUE TITLE
Completion not working

### ISSUE THREAD

**Issue by lopi-py** [pwntester/octo.nvim#337]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Completion seems to not work
![image](https://user-images.githubusercontent.com/70210066/196060232-05e7dc38-95e1-4013-b375-a8e989b5a809.png)

### Describe what you expected to happen
I expect to have completion showing, I can't remember all subcommands (just installed)

### How to reproduce it (as minimally and precisely as possible)

1. have a completion plugin like nvim-cmp
2. enter cmdline
3. type `Octo iss`

### Tell us your environment
I don't think this is related but I had issues with other plugins in the past by this:
OS: **Windows**

### Anything else we need to know?
Completion works on other plugins
![image](https://user-images.githubusercontent.com/70210066/196060346-a5554705-e584-44d0-96fe-64846ad4bee7.png)
Also when I enter a wrong command, nothing happens, would be nice to have a warning o error for this(`vim.notify`)

**Comment by pwntester** [comment]
> Also when I enter a wrong command, nothing happens, would be nice to have a warning o error for this(vim.notify)

This should be fixed, now, please let me know otherwise

**Comment by lopi-py** [comment]
Strange, I'll investigate later
![image](https://user-images.githubusercontent.com/70210066/196164348-6f091b8f-85c9-4ee1-80ae-55fe98da120d.png)

**Comment by lopi-py** [comment]
> > Also when I enter a wrong command, nothing happens, would be nice to have a warning o error for this(vim.notify)
> 
> This should be fixed, now, please let me know otherwise

Yeah it is thanks, I feel the message a little long

**Comment by pwntester** [comment]
> Yeah it is thanks, I feel the message a little long

Yep you are right, too many actions. I shorted it a bit

**Comment by pwntester** [comment]
If it helps, command completion is handled here:
https://github.com/pwntester/octo.nvim/blob/master/lua/octo/commands.lua#L15-L17

**Comment by lopi-py** [comment]
I was testing and seems like `{ complete = require("octocompletion.")... }` callback isn't being called, maybe its a neovim stuff, I'm running nightly(`NVIM v0.9.0-dev-77-gf175ca9f7`)

**Comment by pwntester** [comment]
Weird, just tried with `NVIM v0.9.0-dev-bd7ca10` and it works for me? Does it work if you create you own command with your own completion function?

**Comment by lopi-py** [comment]
I found something very odd, may look like a joke but 
![image](https://user-images.githubusercontent.com/70210066/196513388-24cd22d4-dd73-46b1-a3b2-41644243fa79.png)
it just works if I change the command name in https://github.com/pwntester/octo.nvim/blob/5191478678356c9f1de9a4135bab6756f51dcb30/lua/octo/commands.lua#L15

**Comment by pwntester** [comment]
That is odd indeed, I have done a little refactor of the completion function. Not sure if it will fix your issue, but please give it a try and let me know if it works for you.

**Comment by lopi-py** [comment]
I think I've found the reason, seems related to cmp-cmdline, check
https://gyazo.com/c2601f1c2a2c42814627f551cb80a4af
try the minimal config:
```lua
local on_windows = vim.loop.os_uname().version:match "Windows"

local function join_paths(...)
  return table.concat({ ... }, on_windows and "\\" or "/")
end

local package_root = join_paths(vim.env.TEMP or "/tmp", "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

vim.o.runtimepath = vim.env.VIMRUNTIME
vim.o.packpath = vim.fs.dirname(package_root)

local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      -- plugins here
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      "pwntester/octo.nvim",
      "hrsh7th/nvim-cmp",
      "hrsh7th/cmp-cmdline",
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
  require("packer").sync()
end

local function load_config()
  -- config here
  require("octo").setup {}

  require("cmp").setup {
    snippet = function() end,
  }

  require("cmp").setup.cmdline(":", {
    sources = {
      { name = "cmdline" },
    },
  })
end

if vim.fn.isdirectory(install_path) == 0 then
 vim.fn.system { "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path }
 load_plugins()
 vim.api.nvim_create_autocmd("User", {
   pattern = "PackerComplete",
   callback = load_config,
   once = true,
 })
else
   load_plugins()
   load_config()
end
```

### Steps to reproduce
* `nvim -u minimal.lua`
* enter cmdline mode and type `:Octo is`


Completion wont work but if you trigger only `:Octo `  and press tab, it will show proper completions, can you confirm please?

**Comment by lopi-py** [comment]
Ah, again, seems like changing the command name just works
![image](https://user-images.githubusercontent.com/70210066/196558511-fbca288a-6089-42a8-9c10-f651dfc46ce6.png)
this is very very odd

**Comment by pwntester** [comment]
Still works for me with your minimal conf. Both entering `Octo is<tab>` and `Octo <tab>` 

![Recording 2022-10-19 at 09 05 39](https://user-images.githubusercontent.com/125701/196620424-37b051d3-79eb-4fef-8d01-9c92f3f70064.gif)

However, as you can see in the video, cmp-cmdline is showing some options (eg: starting with `r`) where none of them are and Octo options, and iterating through them with `<tab>` gives me the real Octo commands that starts with `r`

**Comment by pwntester** [comment]
Do you have a non-windows machine to test that out?

**Comment by lopi-py** [comment]
> Do you have a non-windows machine to test that out?

no :(


> However, as you can see in the video, cmp-cmdline is showing some options (eg: starting with `r`) where none of them are and Octo options, and iterating through them with `<tab>` gives me the real Octo commands that starts with `r`

This is what I experience, it should show real completions even if you type `:Octo is`(wihout pressing tab), this is done if you change locally the octo command with something like `Oct`, which is weird

**Comment by pwntester** [comment]
This seems to be a cmp-cmdline bug since, if you remove that part of your minimal.lua config, the completion works as expected. But yep, this is really weird, chaning the command to `Octa` makes it work as expected so Im wondering what that plugin is doing that can be affected by the name of the command 🤔

**Comment by lopi-py** [comment]
Well, I haven't touched my config for a good time, I just switched to lazy.nvim and seems to work fine. To be honest, I have no idea what happened lol. Thanks for taking the time to respond to this joke-look issue @pwntester 
![image](https://github.com/pwntester/octo.nvim/assets/70210066/fdb5e812-a1a6-44a6-b8b8-19843d81ca4a)
