### ISSUE TITLE
Ability to sort issues/prs

### ISSUE THREAD

**Issue by kristijanhusak** [pwntester/octo.nvim#338]
## Issue Description

Discussion: https://github.com/pwntester/octo.nvim/discussions/336
Type: *feature request*

### Describe what happened (or what feature you want)
Ability to sort issues/PRs by anything that Github api supports.
This is what their docs have https://docs.github.com/en/graphql/reference/input-objects#issueorder

I would expect it to work something like this:

```
:Octo pr list states=MERGED sort=CREATED_AT:DESC
```

And maybe if `DESC` is omitted in the sort key to default it to `ASC`:

```
// This sorts ascending by default
:Octo pr list states=MERGED sort=CREATED_AT
```

**Comment by pwntester** [comment]
Thanks, for the idea and suggestion. I though about enabling users to add an `orderBy` configuration property instead since it should not be very common to change the order on each Octo command. What do you think? would that work for you or you have a reason to specify a different orderBy order on each `Octo` invocation?

**Comment by kristijanhusak** [comment]
Configuration works perfectly for me, since I just want to have similar experience to GitHub sorting, which is created_at desc by default. 
What do you think about setting it as a general default rule? I believe most people would expect to have the same sorting like in browser view.

**Comment by pwntester** [comment]
Yep, I think that is a better default. Can you please try https://github.com/pwntester/octo.nvim/pull/339 ?

**Comment by kristijanhusak** [comment]
Works like a charm :)

**Comment by pwntester** [comment]
Nice, thanks for reporting the issue and testing the PR!
