### ISSUE TITLE
List files in a tree view format when reviewing PRs

### ISSUE THREAD

**Issue by ev-agelos** [pwntester/octo.nvim#341]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
When reviewing a PR, list the files in a tree view instead of the bottom buffer. Possibly with the same functionality as github's which lists only the affected from PR files (personally I would like to see all files of a project so i can jump around if needed even to a file that wasn't changed in the PR but has code that I need to check)

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by wd60622** [comment]
Could you add a screenshot of what you would like to see? The GitHub UI has changed a bit since this was opened.

**Comment by ev-agelos** [comment]
Im closing it since i dont use it anymore, i dont even remember what I wanted :|
