### ISSUE TITLE
Add issue to milestone

### ISSUE THREAD

**Issue by divramod** [pwntester/octo.nvim#343]
## Issue Description
feature request

### Describe what you expected to happen
I need to add my issues to milestones on a regular basis.
i can see, that milestones are shown for an issue.
can i change/add a milestone for an issue?
if yes, can you document it somewhere?
if no, can you please implement this feature?

thx for the awesome plugin!

**Comment by pwntester** [comment]
That is not yet possible. Will try to implement it over the xmas break

**Comment by divramod** [comment]
awesome! i am looking forward to :-)

**Comment by pwntester** [comment]
Could not tackle it during the xmas break. Will try to add support as part of the new ProjectsV2 support

**Comment by wd60622** [comment]
This would be great feature to add!

**Comment by wd60622** [comment]
Hi @divramod, I have made a PR for this feature. Please take a look if you are interested!
