### ISSUE TITLE
Allow opening file in context of reviewed branch in Review mode

### ISSUE THREAD

**Issue by marcomayer** [pwntester/octo.nvim#350]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
Quite often when doing code reviews I'd like to open the file in the context of the reviewed branch in a new tab to jump around in code (goto def/ref etc). Currently, I do this by checking out the branch manually and then opening the PR.

It would be awesome if there was a command that opens the file in the tmp folder where the branch is checkout out as the workdir in a new tab.

**Comment by pwntester** [comment]
Hi, Will this work for you? https://github.com/pwntester/octo.nvim/pull/349

**Comment by marcomayer** [comment]
@pwntester yes that looks good! 🚀

**Comment by pwntester** [comment]
Nice, hopefully it will get merged soon. If you are not using commit-level reviews, the PR should be working for you
