### ISSUE TITLE
Thread becomes invisible after Octo thread resolve

### ISSUE THREAD

**Issue by proivk** [pwntester/octo.nvim#362]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
When resolve thread on PR overview dashboard, thread becomes invisible.

Before resolution
![before_resolve](https://user-images.githubusercontent.com/42062047/214010818-a76b9200-ae2d-4187-bb02-e1a3b24fb898.jpg)

After resolution
![after_resolve](https://user-images.githubusercontent.com/42062047/214010955-d56f6349-1f32-4ef2-826f-17f30fa3ade0.jpg)

### Describe what you expected to happen
Thread becomes collapsed, marks as resolved stays visible
![desired](https://user-images.githubusercontent.com/42062047/214011597-4a2fcf78-3d71-485a-8145-939411a54285.jpg)

### How to reproduce it (as minimally and precisely as possible)

1. `Octo pr list`
2. Open PR with not resolved comments/threads
3. On PR view try to resolve thread by typing `Octo thread resolve`

### Tell us your environment
iTerm2
nvim 0.8.0
MacOs
octo plugin latest
tried with EdenEast/nightfox.nvim and projekt0n/github-nvim-theme themes.

**Comment by bradleyjones** [comment]
Also experiencing this behaviour, as a temporary work around I've been reloading the PR with `:e!` so it shows the resolved thread collapsed as expected.
