### ISSUE TITLE
Feature request: Get the permalink for a line

### ISSUE THREAD

**Issue by eivindjahren** [pwntester/octo.nvim#363]
## Issue Description

Type:  *feature request*

I would like to yank the permalink for the line the cursor is on so that it can easily be put into an issue.

### Describe what you expected to happen

When creating an issue with octo one often needs to refer to lines in the main branch. To do so from inside neovim it would be great to be able to just get the permalink for the file under the cursor for the branch that is checked out. So I would like to:

1. checkout main branch
2. Go to a specific line in a file
3. yank the permalink to that line
4. Use Octo issue create to open a new issue
5. paste the permalink into the issue

**Comment by pwntester** [comment]
Does https://github.com/ruifm/gitlinker.nvim do what you want?

**Comment by eivindjahren** [comment]
It does, thank you!
