### ISSUE TITLE
Add code formatting

### ISSUE THREAD

**Issue by lukas-reineke** [pwntester/octo.nvim#37]
Are you open to format the code with `luafmt`?
The code is a bit messy, with mixed 2 and 4 space indentation etc.

No judgment what so ever, I'm just super excited about this and want to help out.
And consistent code would help make contributions easier.

**Comment by pwntester** [comment]
Sure, feel free to send a PR reformating code where needed. I tried to use 2 spaces indentation, but it may not be 💯 consistent. Also, Im new to lua so feel free to suggest any refactoring to get the code more idiomatic.
