### ISSUE TITLE
treesitter markdown parser complaining about filetype_to_parsername

### ISSUE THREAD

**Issue by catgoose** [pwntester/octo.nvim#374]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
Treesitter is issuing a warning:
`filetype_to_parsername is deprecated, please use 'vim.treesitter.language.register`

### Describe what you expected to happen
No warnings

### How to reproduce it (as minimally and precisely as possible)

1. Configure treesitter as per the README for markdown parsing
```lua
local ft_to_parser = require "nvim-treesitter.parsers".filetype_to_parsername
ft_to_parser.octo = "markdown"
```
2. Start neovim

### Tell us your environment
Ubuntu 22.04, neovim nightly

**Comment by timtyrrell** [comment]
> vim.treesitter.language.register('markdown', 'octo')

https://github.com/nvim-treesitter/nvim-treesitter/pull/4296

**Comment by pwntester** [comment]
Thanks @timtyrrell !
