### ISSUE TITLE
Octo builtin

### ISSUE THREAD

**Issue by joshmedeski** [pwntester/octo.nvim#377]
As a user, when I run `Octo` I want to see a list of built-in commands available to run.

It would be great if we could borrow from what `Telescope` does and show a Telescope popup of all available built-in commands from Octo if it's run on it's own. It currently just says "Missing Argument"

<img width="1180" alt="Screenshot 2023-03-01 at 12 07 39 PM" src="https://user-images.githubusercontent.com/2036594/222225157-6fe28d42-5f36-43ba-b4ee-fc24948dcc5f.png">

**Comment by jarviliam** [comment]
This has been merged in now and can be enabled via the `enable_builtin` option 👍

**Comment by joshmedeski** [comment]
Thanks!
