### ISSUE TITLE
Support for lua-date

### ISSUE THREAD

**Issue by lukas-reineke** [pwntester/octo.nvim#38]
I think you saw how I used `lua-date` in my plugin.
I would be happy to add this here.
It would format all dates to be more human-readable, or fallback silently to how it is now if `lua-date` is not installed.

**Comment by pwntester** [comment]
Sure, that would be nice. I had that in my todo list but wanted to find a solution that would not require any external dep.

**Comment by lukas-reineke** [comment]
Yeah I spend some time trying to find a solution that doesn't require a dependency, but didn't find anything easy.

lua-date is only ~700 loc, maybe this plugin could just ship a copy. Or rip out the part that's needed.

**Comment by pwntester** [comment]
I would prefer to ship just the part needed, not every neovim user will have luarocks installed
