### ISSUE TITLE
bug: `Octo reviewer add` command resets existing reviewers

### ISSUE THREAD

**Issue by metalelf0** [pwntester/octo.nvim#386]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

I'm trying to add two reviewers to a PR I'm creating.

The commands I used are:

```
Octo reviewer add first_user
Octo reviewer add second_user
```

I'd expect the PR to have both users as reviewers, however only `second_user` ends up as a PR reviewer.

### Describe what you expected to happen

I'd expect the PR to have both users as reviewers.

### How to reproduce it (as minimally and precisely as possible)

See above.

### Tell us your environment

Neovim latest HEAD, last version of this plugin, github repo for the PR being created is private.

**Comment by Enigama** [comment]
any move here?

**Comment by pwntester** [comment]
Sorry for the late response. Should be fixed now. Let me know and reopen otherwise
