### ISSUE TITLE
[request] change to use github cli or add pull request feature ?

### ISSUE THREAD

**Issue by windwp** [pwntester/octo.nvim#4]
Do you want to change to use github-cli or add pull request checkout function?
I know that github-cli will call github api too but it has more feature and easy to use
https://github.com/nvim-telescope/telescope.nvim/pull/305

**Comment by pwntester** [comment]
That looks awesome! Initially I thought about using GH CLI but didnt want to bring in any "unjustified" dependencies. But I can see how it can help solving problems such as pagination or rate limits. I dont know if it will be possible to get all the info we need from the CLI though, so it may only be valid in some places.

Octo.nvim is already [using telescope](https://github.com/pwntester/octo.nvim/blob/master/lua/octo/menu.lua#L26-L109) so if you look for a home for those pickers, it would be nice to integrate them here (or have them in `nvim-telescope/telescope-github.nvim` as proposed by @tjdevries and then make that a dep for octo.nvim)

**Comment by weilbith** [comment]
Voting for this feature! :+1:

**Comment by pwntester** [comment]
Awesome, didnt know about the `api` command. Will definitely migrate it to use cli 👍🏻

**Comment by pwntester** [comment]
@weilbith Just finished migrating to GH CLI, can you please check the [ghcli](https://github.com/pwntester/octo.nvim/tree/ghcli) branch? any help testing it is welcome!

**Comment by weilbith** [comment]
Feedback in the PR. :upside_down_face:

**Comment by pwntester** [comment]
Implemented in 6ec594dbd3261919f460395c62e3aca9b7f20de1
