### ISSUE TITLE
`Octo repo list` throws error

### ISSUE THREAD

**Issue by Subjective** [pwntester/octo.nvim#401]
## Issue Description
The `:Octo repo list` command throws the below error. For some reason, executing another command (e.g. `:Octo search`) beforehand allows it to work correctly.

Type: *bug report*

### Describe what happened (or what feature you want)
```
Error message:
Error executing Lua callback: ...m/lazy/octo.nvim/lua/octo/pickers/telescope/provider.lua:925: bad argument #2 to 'graphql' (value expected)
stack traceback:
	[C]: in function 'graphql'
	...m/lazy/octo.nvim/lua/octo/pickers/telescope/provider.lua:925: in function 'repos'
	...a/.local/share/nvim/lazy/octo.nvim/lua/octo/commands.lua:138: in function 'a'
	...a/.local/share/nvim/lazy/octo.nvim/lua/octo/commands.lua:356: in function 'octo'
	...a/.local/share/nvim/lazy/octo.nvim/lua/octo/commands.lua:16: in function <...a/.local/share/nvim/lazy/octo.nvim/lua/octo/commands.lua:15>
```

![Screen Recording 2023-05-29 at 10 21 36 PM](https://github.com/pwntester/octo.nvim/assets/56745535/4ffaca3d-8a13-47c4-ae16-cb99c540ae96)

### Describe what you expected to happen
I expect telescope to show a list of my repos. 

### How to reproduce it (as minimally and precisely as possible)

1. `:Octo repo list`

### Tell us your environment
MacOS 13.3
Neovim v0.9.1

**Comment by Subjective** [comment]
@pwntester It works now, thanks!

**Comment by pwntester** [comment]
My fault, I left a debug print around. should be ok now
