### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Enigama** [pwntester/octo.nvim#408]
## Issue Description

feature request

### Describe what you expected to happen
Hi, amazing plugin, thanks a lot.
I would like to have some solution to past screenshots to PR I don't know is it possible.
I also interesting on mention some people inside PR description
like this: @Enigama  and have a popup with autocomplettion like for reviewers.

**Comment by pwntester** [comment]
Sorry for the late response:

> I would like to have some solution to past screenshots to PR I don't know is it possible.

There are plugins to paste the image into a file and add a link to that file. Eg:
https://github.com/ekickx/clipboard-image.nvim

However, they do not upload the image to GitHub as pasting in the browser does. This may be implemented externally but its not in Octo's roadmap to add this feature. At list until [image rendering in terminal](https://github.com/3rd/image.nvim/) gets more mature.

> I also interesting on mention some people inside PR description

This is already [supported](https://github.com/pwntester/octo.nvim/blob/master/README.md#-faq)
