### ISSUE TITLE
bug: Octo issue list problem

### ISSUE THREAD

**Issue by dpetka2001** [pwntester/octo.nvim#410]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)
When inside a repo in Neovim, I issue the command `Octo issue list` to see listed opened issues and the following error popups
```
Error executing vim.schedule lua callback: ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:443: Error executing lua: vim/filetype.lua:0: attempt to index a number value
stack traceback:
	vim/filetype.lua: in function ''
	vim/filetype.lua: in function 'match'
	...m/lazy/telescope.nvim/lua/telescope/previewers/utils.lua:37: in function 'filetype_detect'
	...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:449: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:443>
	[C]: in function 'nvim_buf_call'
	...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:443: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:437>
stack traceback:
	[C]: in function 'nvim_buf_call'
	...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:443: in function <...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:437>
```
The same also happens when trying to list the PRs.

### Describe what you expected to happen
Not throw the error.

### How to reproduce it (as minimally and precisely as possible)

1. Cd into a repo on your local filesystem
2. Open a file with Neovim and issue the command `Octo issue list`
3. Error popups

### Tell us your environment
Linux Mint 21.1 with Neovim nightly commit c53953b40 built from source

**Comment by jarviliam** [comment]
Opened a fix for it on the telescope repository: https://github.com/nvim-telescope/telescope.nvim/pull/2565

**Comment by dpetka2001** [comment]
Thank you for your swift response.
