### ISSUE TITLE
highlighting of badges is funky?

### ISSUE THREAD

**Issue by mizlan** [pwntester/octo.nvim#412]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

<img width="438" alt="Screen Shot 2023-06-17 at 9 02 14 AM" src="https://github.com/pwntester/octo.nvim/assets/44309097/a68fc3f0-6dbb-4c7d-a7b4-c0398791ef78">

The badges use the special char but it's highlighted wrong.

### Describe what you expected to happen

The badge should be properly highlighted (it seems Octo should tack on a default highlight group for this)

### How to reproduce it (as minimally and precisely as possible)

1. Use Octo.nvim
2. Set colorscheme to Rose-pine or Everforest , seoul256, tokyonight (tested with those 4)
3. see it

### Tell us your environment

unnecessary

**Comment by pwntester** [comment]
Hi, probably those themes are missing the Octo highlight groups. What are your colours for:
- OctoBubbleBlue
- OctoBubbleDelimiterBlue
- OctoBubbleYellow
- OctoBubbleDelimiterYellow
- OctoBubbleGreen
- OctoBubbleDelimiterGreen
- OctoBubbleRed
- OctoBubbleDelimiterRed

**Comment by rodhash** [comment]
Similar issue happening here, in my case it seems to be a bit more broken.

<img width="452" alt="image" src="https://github.com/pwntester/octo.nvim/assets/29671981/726ca678-2c4d-4d10-bc9b-35c7840f7578">



iTerm `3.4.22`
Nvim `v0.9.4`
Octo `604fad12`


These are my colors (my custom teme):

<img width="697" alt="image" src="https://github.com/pwntester/octo.nvim/assets/29671981/67460398-a903-460d-8ac7-572395bf2ad8">


I also tried other colorschemes such as gruvbox and tried using kitty instead but same issue. I even installed 4 or 5 different NF fonts but no luck so far.

any idea?

**Comment by rodhash** [comment]
Here a print screen w/ Kitty, Gruvbox, latest neovim nightly and a new NF:

<img width="687" alt="image" src="https://github.com/pwntester/octo.nvim/assets/29671981/31cef0ce-7777-49bc-930b-f3d3d195ee54">

**Comment by kezhenxu94** [comment]
For everyone in this thread, I've filed a PR (https://github.com/pwntester/octo.nvim/pull/456) to fix this, in case you want to verify.

**Comment by rodhash** [comment]
Thank you .. gave it a try and its looking way better now, some fonts now can render it but I just noticed something, apparently many other nerd fonts seem to have problem with this rounded char (including the font that I most enjoy lol)

One example is Hack font showing this very tiny "space" between the rounded char and the string:

<img width="254" alt="image" src="https://github.com/pwntester/octo.nvim/assets/29671981/ab796097-8120-4684-ab99-e4979e2a45c6">

Some fonts like Victor Mono seems to render it properly.. it's time to look for a new font I guess, or patching mine

<img width="245" alt="image" src="https://github.com/pwntester/octo.nvim/assets/29671981/7698e34a-a90b-4393-abc2-ccb42972b739">

**Comment by pwntester** [comment]
Thanks for the fix @kezhenxu94
