### ISSUE TITLE
Filter assignees to current repo

### ISSUE THREAD

**Issue by Linuus** [pwntester/octo.nvim#423]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

When assigning a user to a PR or Issue it searches for all users on Github. Is it possible to only show users with access to your repo? Like in the Github Web UI you only get relevant users in the dropdown and not everyone on Github.
Hopefully it would speed it up a little bit as well :)

**Comment by GrimalDev** [comment]
Hello, do we have any news on this? The speed is really a problem in this case.

**Comment by wd60622** [comment]
I was playing around with the GraphQL API and found this query which might be useful for at least filtering out some users

```graphql
{
  repository(owner: "<owner>", name: "<repo>") {
    mentionableUsers(first: 100) {
      pageInfo {
        hasNextPage
        endCursor
        startCursor
      }
      nodes {
        login
      }
    }
  }
}
```
