### ISSUE TITLE
Error when cycling through changed files

### ISSUE THREAD

**Issue by bolt12** [pwntester/octo.nvim#439]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

When reviewing a PR and cycling through changed files  with `[q` or `]q` I get an error for some particular files.

Before pressing `]q`:
![image](https://github.com/pwntester/octo.nvim/assets/20261421/d010766c-79c9-4990-b4e6-49806ef20f9d)

after:

![image](https://github.com/pwntester/octo.nvim/assets/20261421/0bec8c22-a664-4e64-9322-df3227875019)

### Describe what you expected to happen

It should go to the next changed file without an error

### How to reproduce it (as minimally and precisely as possible)

1. review: https://github.com/input-output-hk/ouroboros-network/pull/4644
2. cycle through changed files
3. error

**Comment by Danthewaann** [comment]
I have the same problem. I've found that running `git diff` manually with the commit range that octo uses for the commit to review returns an error like so:

```bash
$ git diff a6ca7c6..fa4aef9
fatal: ambiguous argument 'a6ca7c6..fa4aef9': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

So this is likely what is causing your problem too.

**Comment by Danthewaann** [comment]
Actually I think I now what the problem is. 

After just running `git pull` locally and then re-running `:Octo review commit` and selecting the commit that was failing before it now successfully views it without throwing up any error.

So you need to make sure your local copy of the PR branch is up to date with the remote one it seems.
