### ISSUE TITLE
Feature Request: Develop Issue Command

### ISSUE THREAD

**Issue by arnold-c** [pwntester/octo.nvim#443]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

I'm not sure if this is already implemented (I tried looking and couldn't find any documentation or mentions in the discussions/issues about it, but apologies if I just missed it), but I think it would be useful to be able to use the `gh issue develop #X --checkout` command to turn an issue into a new branch.

### Describe what you expected to happen

The GitHub CLI has an option to turn an issue into a branch and then check it out on your local machine (among other options).

https://cli.github.com/manual/gh_issue_develop

I think it would be useful to be able to either: 1) open up the Issue list, open an issue in a buffer, and then use an Octo command to be able to send the above command to develop an issue branch; or 2) use an Octo command to bring up a Telescope viewer where you can select an issue to develop, and then you are given a dropdown to select the extra flags you would like to apply (like using templates for issue creation). Option 2) would be cleaner and faster, in my opinion, but likely also be more work.

I would offer to help, but I'm afraid I am not familiar enough with scripting in Lua and Telescope, so I don't think I'd be of much help.

Thanks for your work putting out a great plugin.

**EDIT:** Embarrasingly, I've just seen this discussion https://github.com/pwntester/octo.nvim/discussions/392 right near the top, but I think the feature request is still valid as it potentially provides a mechanism through the CLI to implement this? Please close if you feel it is not required.

**Comment by wd60622** [comment]
I think both options would be very useful. I've been playing around with the GitHub CLI commands required here and it seems like there might be some permission issues when trying to create a linked branched to the upstream repo from a fork.

**Comment by wd60622** [comment]
Hi @arnold-c 

I have implemented this in #609 . 1 and 2 are both available for telescope. However, I haven't implemented 2 for other pickers
