### ISSUE TITLE
Can PRs have a default title?

### ISSUE THREAD

**Issue by aaronmcadam** [pwntester/octo.nvim#444]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

I'd like `pr create` to use a default title of the latest or first commit like the `gh` CLI works. This would save me a bit of time because I often need to rewrite the title based on a commit message.

### Describe what you expected to happen
I expected the title to default to my latest or first commit message.

### How to reproduce it (as minimally and precisely as possible)

1. Run `Octo pr create`
2. See that you have to manually input a title
3. Wish that this functionality was in Octo.nvim

### Tell us your environment
OS: macOS 14.1 23B74 arm64
Host: Mac14,6
Kernel: 23.1.0
Uptime: 23 hours, 37 mins
Packages: 106 (brew)
Shell: fish 3.6.1
Resolution: 3008x1692, 3008x1692
DE: Aqua
WM: yabai
Terminal: zellij
CPU: Apple M2 Max
GPU: Apple M2 Max
Memory: 9036MiB / 98304MiB

**Comment by joshmedeski** [comment]
Looks like there is some logic already attempting to get a default title, perhaps it just needs updated?
https://github.com/pwntester/octo.nvim/blob/e933611c74cb735c00d0db8ca94533bec1444bf0/lua/octo/commands.lua#L905

**Comment by aaronmcadam** [comment]
> Looks like there is some logic already attempting to get a default title, perhaps it just needs updated?
> 
> https://github.com/pwntester/octo.nvim/blob/e933611c74cb735c00d0db8ca94533bec1444bf0/lua/octo/commands.lua#L905

Yeah, I know I saw it work once or twice before, but 99% of the time, it fails to get a default title.

**Comment by aaronmcadam** [comment]
According to this, it should already be taking the last commit: https://github.com/pwntester/octo.nvim/blob/e933611c74cb735c00d0db8ca94533bec1444bf0/lua/octo/commands.lua#L891C33-L891C33

**Comment by aaronmcadam** [comment]
ahh running the same git command locally, I get:

```
❯ git log -1 --pretty=%B
error: cannot run difftastic: No such file or directory
organise imports skip-ci
```

So the pretty formatted is failing to find my diff tool (difftastic)

**Comment by vitorf7** [comment]
> According to this, it should already be taking the last commit: https://github.com/pwntester/octo.nvim/blob/e933611c74cb735c00d0db8ca94533bec1444bf0/lua/octo/commands.lua#L891C33-L891C33

Interesting. If you were to normally open it in Github, most of the time for me it tends to use the first commit I believe, which is why my first commit tends to be the `conventional commits` title that I intend my PR to have as well as my squash-merge since I tend to then remove most of the body (although that is a different use case that I think someone has created an issue ticket as well for).

**Comment by aaronmcadam** [comment]
So fixing my git log command didn't help. I see the following messages when trying to create a new PR:

![CleanShot 2023-11-03 at 16 58 59@2x](https://github.com/pwntester/octo.nvim/assets/37928/502399e1-1899-494c-818f-b35a19e89802)

**Comment by aaronmcadam** [comment]
That `OctoEditable xxx cleared` looks suspect to me.

**Comment by joshmedeski** [comment]
Fixed it, a little pair programming with @aaronmcadam

**Comment by pwntester** [comment]
Thanks for the fix folks. Appreciate it!
