### ISSUE TITLE
Removed files not showing up in PR review panel

### ISSUE THREAD

**Issue by Eryx5502** [pwntester/octo.nvim#461]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
When using Octo for reviewing a PR, I noticed that removed files doesn't show up on the bottom panel of the review layout, where all other modified files do appear. Unless I'm missing something, this makes impossible to know if you're missing some changes (i.e., the files removed completely) from the PR you're reviewing through Octo interface.

### Describe what you expected to happen
I would expect the removed files appear on the bottom panel and once selected the upper right panel were empty while the upper left displayed the old (removed) version of the file.

### How to reproduce it (as minimally and precisely as possible)

1. Take a PR with deleted files among its changes.
2. :Octo review start (actually, I did it resuming a review created from github web)
3. Deleted files won't show in the bottom panel.

### Tell us your environment
Nvim 0.10.0-dev inside WSL2

**Comment by pwntester** [comment]
Just tested with https://github.com/pwntester/octo-tests/pull/21 and I can see the removed file (test1.lua) in the changes panel:


![Image](https://github.com/pwntester/octo.nvim/assets/125701/715f30a6-7eea-481c-bf1b-32e83a0dba6c)

Is your PR public so I can take a look?
