### ISSUE TITLE
Octo.nvim runs a slow network-IO-bound shell command during startup

### ISSUE THREAD

**Issue by idanarye** [pwntester/octo.nvim#478]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

After I updated my plugins, Neovim's startup time noticably increased to more than a second. A bit of profiling led to Octo.nvim - specifically to the [recently added `setup` function of the `octo.gh` module](https://github.com/pwntester/octo.nvim/commit/842e5ee03d9d9ca0013fa1d98453ad37c42098b4#diff-ef4ee25827d4565dceaefe93a386ceee4ecdd267580bf0e0c96e6ab750b6ba96). This function runs `gh auth status` command, which needs to make network requests against GitHub and delays the entire startup process.

### Describe what you expected to happen

This command should run asynchronously so that it wouldn't block Neovim's startup. That is - Octo.nvim's setup will not be complete when `require'octo'.setup{}` returns, but instead progress in the background.

### How to reproduce it (as minimally and precisely as possible)

1. Install Octo.nvim
2. Configure Neovim to run `require'octo'.setup{}` on startup.
3. Run `nvim`

**Comment by pwntester** [comment]
Thanks for reporting it. Would you mind testing https://github.com/pwntester/octo.nvim/pull/479 and checking if it fixes the issue for you?

**Comment by idanarye** [comment]
Yup. That solved it.
