### ISSUE TITLE
BUG: cannot request project v2, missing scope 'read:project'

### ISSUE THREAD

**Issue by sajjathossain** [pwntester/octo.nvim#487]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
Getting this message whenever I open neovim for the first time
![image](https://github.com/pwntester/octo.nvim/assets/59532941/7c788d93-1202-4033-849b-630cb7693825)

### Describe what you expected to happen
This message was not there before.

### How to reproduce it (as minimally and precisely as possible)

1. Open neovim

### Tell us your environment
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by pwntester** [comment]
Please check https://github.com/pwntester/octo.nvim/issues/480#issuecomment-1894798807

**Comment by pwntester** [comment]
Will add a note to the README
