### ISSUE TITLE
Mapping `<c-v>`, `<c-s>`, `<c-t>` seems not work as expected, picker fzf-lua

### ISSUE THREAD

**Issue by MadKuntilanak** [pwntester/octo.nvim#516]
## Issue Description

Type: *bug report* 

### Describe what happened
Except `<CR>`, both mapping pickers (fzf-lua or telescope) do not appear to be working as expected.

1. `<c-t>` does not define an open tab as expected.
2. `<c-v>` does not define a vertical window as expected.
3. `<c-s>` does not define a split window as expected.

### Tell us your environment
Neovim nightly

### Anything else we need to know?
https://github.com/pwntester/octo.nvim/blob/1e2376ac6966805be9967f4ea0e4cf7c750f8214/lua/octo/pickers/fzf-lua/pickers/utils.lua#L57
I use `fzf-lua`so fixed it with this:

```lua
--[[
  Open the entry in a buffer.

  @param command One of 'default', 'horizontal', 'vertial', or 'tab'
  @param entry The entry to open.
]]
function M.open(command, entry)
  if command == "default" then
    vim.cmd [[buffer %]]
  elseif command == "horizontal" then
    vim.cmd [[sp %]]
  elseif command == "vertical" then
    vim.cmd [[vsp %]]
  elseif command == "tab" then
    vim.cmd [[tabnew %]]
  end
  utils.get(entry.kind, entry.repo, entry.value)
end

```

what do you think?

**Comment by milogert** [comment]
OK, after getting neovim nightly installed with my flake config I still don't see this issue. What command are you using to do a search in `fzf-lua`? I tried this with `Octo pr search`, `Octo issue search`, and `Octo search` and all seemed to work ok.

**Comment by MadKuntilanak** [comment]
oh no. my bad
yes, after solving the fzf config there is no mistake 

you can close this issue

**Comment by pwntester** [comment]
Thanks for looking into it @milogert!
