### ISSUE TITLE
Cannot request projects v2, missing scope 'read:project'

### ISSUE THREAD

**Issue by Integralist** [pwntester/octo.nvim#564]
## Issue Description

*bug report*

### Describe what happened (or what feature you want)

Every time I open nvim I see the message:

```
Cannot request projects v2, missing scope 'read:project'
```

This is even after following the instructions in the README to run:

```
gh auth refresh -s read:project
```

### Describe what you expected to happen

No message to appear.

### How to reproduce it (as minimally and precisely as possible)

1. Open nvim

### Tell us your environment

MacOS 14.4.1
NVIM v0.10.0

**Comment by Kyren223** [comment]
This also happened to me, any idea how to fix this would be nice

**Comment by Integralist** [comment]
I found in the README a way to hide the error message.

**Comment by Kyren223** [comment]
@Integralist I would want a way to fix the issue rather than suppressing it

**Comment by mattlbrr** [comment]
@Integralist @Kyren223 You have to also set
  `default_to_projects_v2 = true`
  See the second part of the if condition here: https://github.com/pwntester/octo.nvim/blob/0134169886958f3874f16eed7fe73d906a3e7e17/lua/octo/gh/init.lua#L103
  See the code condition: 
```
    "pwntester/octo.nvim",
    dependencies = {
      'nvim-lua/plenary.nvim',
      'nvim-telescope/telescope.nvim',
      'kyazdani42/nvim-web-devicons',
    },
    config = function()
      require("octo").setup({
        default_to_projects_v2 = true,
      })
    end,

**Comment by emilkje** [comment]
This happened to me today as well with a fresh installation. Thanks for the fix @mattlbrr :)

It would be great with a more informative error message, or better yet, if the plugin could solve this without erring out with a non-actionable message.

**Comment by relausen** [comment]
Thanks for the analysis, @mattlbrr! The problem is that the `and` condition can be false in two ways, and the `elseif` tries to handle both. Classic logic error when testing multiple conditons in one conditional.

**Comment by wd60622** [comment]
@relausen interested in making a PR?

**Comment by relausen** [comment]
Sure - I'll give it a go.
