### ISSUE TITLE
Octo isn't authenticating even though gh is working properly

### ISSUE THREAD

**Issue by benelan** [pwntester/octo.nvim#568]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

Octo isn't realizing that I'm authenticated through `gh`. I tried switching between `ssh` and `https`, which has not effect. I'm using `github.com` as my remote, so there shouldn't be any issues there.

I am getting a rate limit error when trying to run any Octo commands (e.g. `:Octo pr list`) due to the auth issue:

```
gh: API rate limit exceeded for ************. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) (HTTP 403)
```
Running `:!gh pr list` does show the list of PRs. 

Running `:lua print(require("octo.gh").get_user_name())` does not print my username.

Running `!gh auth status` shows that I am logged in:

```
github.com
  ✓ Logged in to github.com account benelan (keyring)
  - Active account: true
  - Git operations protocol: https
  - Token: ***************************************
  - Token scopes: 'gist', 'read:org', 'repo'
```

I also checked my rate limiting via `gh api /rate_limit` and I'm not at the limit:

```
{
  "resources": {
    "core": { "limit": 5000, "used": 0, "remaining": 5000, "reset": 1719617580 },
    "search": { "limit": 30, "used": 0, "remaining": 30, "reset": 1719614040 },
    "graphql": { "limit": 5000, "used": 10, "remaining": 4990, "reset": 1719615254 },
    "integration_manifest": { "limit": 5000, "used": 0, "remaining": 5000, "reset": 1719617580 },
    "source_import": { "limit": 100, "used": 0, "remaining": 100, "reset": 1719614040 },
    "code_scanning_upload": { "limit": 1000, "used": 0, "remaining": 1000, "reset": 1719617580 },
    "actions_runner_registration": { "limit": 10000, "used": 0, "remaining": 10000, "reset": 1719617580 },
    "scim": { "limit": 15000, "used": 0, "remaining": 15000, "reset": 1719617580 },
    "dependency_snapshots": { "limit": 100, "used": 0, "remaining": 100, "reset": 1719614040 },
    "audit_log": { "limit": 1750, "used": 0, "remaining": 1750, "reset": 1719617580 },
    "code_search": { "limit": 10, "used": 0, "remaining": 10, "reset": 1719614040 }
  },
  "rate": { "limit": 5000, "used": 0, "remaining": 5000, "reset": 1719617580 }
}

```

### Describe what you expected to happen

I expect octo.nvim to properly determine that I'm authenticated and find my username.

### How to reproduce it (as minimally and precisely as possible)

1. Run `:Octo pr list`
2. See the rate limit error

### Tell us your environment

Pop!_OS 22.04 LTS x86_64

Swaywm

gh version 2.52.0 (2024-06-24) (installed using [these steps](https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt))

NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068

### Anything else we need to know?

Please let me know if there is anything else I can provide to help troubleshoot, since I doubt you can repro on your end.

I found #466 through a comment in the source code but the workaround of setting `vim.g.octo_viewer` didn't work for me.

**Comment by benelan** [comment]
I downgraded to `gh version 2.51.0` by [installing from source](https://github.com/cli/cli/blob/f71d3f75e3e21c0f96ffb0ec3c64bf48490075af/docs/source.md), which resolved the issue. So something changed in `v2.52.0` that broke this plugin for me.

**Comment by benelan** [comment]
I tried updating back to `v2.52.0` and it works now, not sure what happened. Sorry for the false alarm!

**Comment by MikaelElkiaer** [comment]
I am still experiencing this issue, running gh version `2.60.0`.

Running `:lua print(require("octo.gh").get_user_name())` I see

```
   Error  11:06:27 AM notify.error Octo.nvim github.com
  X Failed to log in to github.com account MikaelElkiaer (/home/mikaelki/.config/gh/hosts.yml)
  - Active account: true
  - The token in /home/mikaelki/.config/gh/hosts.yml is invalid.
  - To re-authenticate, run: gh auth login -h github.com
  - To forget about this account, run: gh auth logout -h github.com -u MikaelElkiaer
```

while running `!gh auth status` yields

```
✓ Logged in to github.com account MikaelElkiaer (keyring)
  - Active account: true
  - Git operations protocol: https
  - Token: gho_************************************
  - Token scopes: 'gist', 'read:org', 'read:packages', 'read:project', 'repo', 'workflow'
```

**Comment by pwntester** [comment]
Hi @MikaelElkiaer 

This seems a different issue since you are not getting rate limited.

The only diference is that Octo calls `gh auth status --hostname <hostname>` and gets host name from `require("octo.utils").get_remote_host()`. Can you run this command and let me know that is the host name returned?

**Comment by MikaelElkiaer** [comment]
@pwntester Thank you for replying to me.

Here's what I see from some various commands

```
:lua= require("octo.utils").get_remote_host()
  github.com

:lua= require("octo.gh").get_user_name()
  X Failed to log in to github.com account MikaelElkiaer (/home/mikaelki/.config/gh/hosts.yml)
  - Active account: true
  - The token in /home/mikaelki/.config/gh/hosts.yml is invalid.
  - To re-authenticate, run: gh auth login -h github.com
  - To forget about this account, run: gh auth logout -h github.com -u MikaelElkiaer

:lua= require("octo.gh").get_user_name("github.com")
  X Failed to log in to github.com account MikaelElkiaer (/home/mikaelki/.config/gh/hosts.yml)
  - Active account: true
  - The token in /home/mikaelki/.config/gh/hosts.yml is invalid.
  - To re-authenticate, run: gh auth login -h github.com
  - To forget about this account, run: gh auth logout -h github.com -u MikaelElkiaer
```

It seems to me that it is an error when the plugin (Plenary) calls `gh` as opposed to me calling it directly.
Somehow gh does not recognize that it is using keyring and therefore expects a token in my `hosts.yml`.

Just to be clear, it looks like this:

```yaml
# hosts.yml
github.com:
    git_protocol: https
    users:
        MikaelElkiaer:
    user: MikaelElkiaer
```

**Comment by pwntester** [comment]
Your hosts.yml looks similar to mine, so that should not be a problem. Perhaps is related with the environment variables. Can you please check if using just the subset defined by Octo get you a similar error in the shell?

**Comment by MikaelElkiaer** [comment]
I am suspecting that for some reason `gh auth status` does not properly recognize the keyring when run in this way: https://github.com/pwntester/octo.nvim/blob/3f9f945401f4dbbeb7ecee5a5585e26ef743105c/lua/octo/gh/init.lua#L52-L57.

I base this on the first line of the output for the two commands:

```
:lua= require("octo.gh").get_user_name()
  X Failed to log in to github.com account MikaelElkiaer (/home/mikaelki/.config/gh/hosts.yml)

:!gh auth status
  ✓ Logged in to github.com account MikaelElkiaer (keyring)
```

Note that the when run via Octo it hints that it is using the hosts.yml, while it uses the keyring for the external command.

**Comment by wd60622** [comment]
Hi @MikaelElkiaer 

Do you have documentation on this env variable? Is there a harm in including for everyone? Maybe it can assign if it exists

**Comment by MikaelElkiaer** [comment]
> Hi @MikaelElkiaer
> 
> Do you have documentation on this env variable? Is there a harm in including for everyone? Maybe it can assign if it exists

I dare not say.
Perhaps it is better to add this info in the FAQ section of the readme.
