### ISSUE TITLE
Fix "1 days ago" grammar

### ISSUE THREAD

**Issue by joshmedeski** [pwntester/octo.nvim#579]
On the comments, if a comment was 1 day ago it reads "1 days ago".

The correct grammar is "1 day ago"

**Comment by joshmedeski** [comment]
I can fix it, just wanted to flag it with you and figure out if there's anywhere else in the code you can think of that could use a similar grammatical improvement.

**Comment by pwntester** [comment]
Thanks Josh! Big fan of sesh here 😄
