### ISSUE TITLE
[Feature Request] add support for mason's gh.cmd

### ISSUE THREAD

**Issue by mao-yining** [pwntester/octo.nvim#582]
## Issue Description

Type: _feature request_

### Describe what happened (or what feature you want)

If I install gh from mason, it will has a gh.cmd in its bin.

Now octo only work when gh.exe was in the env, if I only add gh.cmd in my env , it won't work.

So, I have to add a special env for the gh.exe, it's not pretty.

### Describe what you expected to happen

Add support for mason's gh.cmd.

### How to reproduce it (as minimally and precisely as possible)

1. use mason.nvim install gh
2. keep only a gh.cmd in the env (add /nvim-data/mason/bin in the env
3. start octo

### Tell us your environment

windows 11 neovim v0.10.1

**Comment by wd60622** [comment]
Are you able to use the `gh_cmd` option in the configuration? The mason installation will be a binary on your system. Does that work?

**Comment by mao-yining** [comment]
The gh.exe is well. But when it was transferred by it's cmd. It doesn't work

**Comment by mao-yining** [comment]
Sorry I means it can't be used by octo. When I calls it in other methods such as command line. It works perfect

**Comment by mao-yining** [comment]
Sorry I means it can't be used by octo. When I calls it in other methods such as command line. It works perfect

**Comment by wd60622** [comment]
What error do you get when setting it to the `gh_cmd`?

**Comment by mao-yining** [comment]
I thought that maybe there are something loss in the transfer.
I set gh_cmd="gh.cmd" and it has another wrong 
![图片](https://github.com/user-attachments/assets/8c5f183a-5544-46bb-831c-8c80682797b3)

**Comment by wd60622** [comment]
> I thought that maybe there are something loss in the transfer.
> 
> I set gh_cmd="gh.cmd" and it has another wrong 
> 
> ![图片](https://github.com/user-attachments/assets/8c5f183a-5544-46bb-831c-8c80682797b3)
> 
> 

I was thinking you would set the full path to the binary used by mason

**Comment by mao-yining** [comment]
All right thank you. Thogh I still puzzled by why it doesn't work after transfered, it's a well solution any more.
