### ISSUE TITLE
Time ago is off

### ISSUE THREAD

**Issue by joshmedeski** [pwntester/octo.nvim#584]
As a user, I want my time ago to be accurate.

## Issue Description

I'm having two issues.

The first is it's showing `0 days ago` even though when I look at the code it seems obvious to me that it should be skipping to the hour logic.

<img width="970" alt="SCR-20240827-oilt" src="https://github.com/user-attachments/assets/35847fe5-e39e-405d-b361-c1fbfd65e98f">

The second is the time itself is off, maybe it's a timezone conversion issue but in this example it says 6 hours ago but it was only a few minutes ago that I made this comment.
<img width="432" alt="SCR-20240827-omxo" src="https://github.com/user-attachments/assets/69488db1-00c2-413d-9416-634e12e3949e">

Perhaps these items are related, but I haven't been able to figure it out yet.

### Describe what happened (or what feature you want)

I want it to show the correct "time ago" on comments

### How to reproduce it (as minimally and precisely as possible)

1. Create a comment in a PR
2. Look at the "time ago" inline-text and see "0 days ago"

**Comment by wd60622** [comment]
I've opened a PR to this. This has fixed it for me in PRs and Issues. I may be missing some scenarios so feel free to take a look.

**Comment by wd60622** [comment]
Hi @joshmedeski 
Have these two cases been resolved for you?

**Comment by joshmedeski** [comment]
Yes, thanks!
