### ISSUE TITLE
Open in popus

### ISSUE THREAD

**Issue by tami5** [pwntester/octo.nvim#59]
Hey @pwntester I'm just getting started with octo and seems amazing. I wonder if its possible to have things open as popup as obsessed to opning in main window, also toggles. I think it makes sense, since users would open issues in split of second and don't missup their layout, or they'd like to have it temp hidden for looking up stuff in the code base.

Thanks again @pwntester

**Comment by pwntester** [comment]
do you mean the issue/pr buffer? Im not sure about it since you normally want to perform other actions in those buffers (eg: `Octo pr checks`)

also, those are single buffers so they should not break the window layout. The commands that can break the layout are `Octo pr reviews` and `Octo review start` but those open new tabs to preserve the window layout.

can you give a specific example of a buffer you would like to see in a popup window?

**Comment by tami5** [comment]
I do mean all buffers, and for check it can be on top. the other two command didn't work for me for some reason.

I think it would be great as an option or as an arg the can be passed, and toggled on and off. If you like I can work on the popup part and provide an easy interface for it to be used in if then else statement where the buffers get opened. The toggling part maybe a bit tricky.

**Comment by pwntester** [comment]
> the other two command didn't work for me for some reason.
`Octo pr reviews` is being actively developed in a PR
`Octo review start` should work but should only show a qf window populated with changes and a diff split windows, comments are not yet implemented. do you get an error when running that command?

> I think it would be great as an option or as an arg the can be passed, and toggled on and off.
Normally you will want to interact with those buffers, write new comments, add reactions, etc and I think float windows are better for menus or "read" only buffers, but if you want to give it a try, I will be glad to merge it as an opt-in toggle. thanks!

**Comment by weilbith** [comment]
I know, looking at PR reviews works a bit different, but having a workflow more similar to the GH web version it would cool to just open a PR and in this buffer get "previews" of the review conversations without opening a full review in a new tab. I assume/hope this already gets improved with some folds of #80 so you can unfold discussions of a PR inside the PR buffer. But then it would be still great to preview the code that it relates to with a floating window. Thinking about it this would be pretty damn awesome in my opinion. So you have this quick and dirty discussion style as on the webapp, but also the ability to handle reviews with full code editor capabilities if needed.

**Comment by weilbith** [comment]
Another useful pop-up feature I just "discoverd" is for GH references. So in first place issue/PR numbers. In the web-version i can simply hover them. Would be amazing to get the title, author, description, ...
I just look at a PR and there is reference to an issue. I don't want to open, just know which one he means...

**Comment by pwntester** [comment]
> Another useful pop-up feature I just "discoverd" is for GH references. So in first place issue/PR numbers. In the web-version i can simply hover them. Would be amazing to get the title, author, description, ...
> 
> I just look at a PR and there is reference to an issue. I don't want to open, just know which one he means...
> 
> 
> 
> EDIT: this combined with `CursorHold` :exploding_head: 

Nice idea, please file a separate issue for this hover idea 👍🏼

**Comment by pwntester** [comment]
> I know, looking at PR reviews works a bit different, but having a workflow more similar to the GH web version it would cool to just open a PR and in this buffer get "previews" of the review conversations without opening a full review in a new tab. I assume/hope this already gets improved with some folds of #80 so you can unfold discussions of a PR inside the PR buffer. But then it would be still great to preview the code that it relates to with a floating window. Thinking about it this would be pretty damn awesome in my opinion. So you have this quick and dirty discussion style as on the webapp, but also the ability to handle reviews with full code editor capabilities if needed.

👍🏼 Please add all these ideas to the issue for incorporating review threads in the main PR buffer

**Comment by pwntester** [comment]
Now that this ideas have been dumped in new issues, I will close this one. Please file new issues for specific new popup related features
