### ISSUE TITLE
Error escaping newline characters in graphql mutations

### ISSUE THREAD

**Issue by GuillaumeLagrange** [pwntester/octo.nvim#590]
## Issue Description

Type: *bug report*

### Describe what happened

I do not know what I changed in my setup, but since at least a few days, the gh graphql calls fail as soon as there are multiple lines in the content of what I am updating.

It used to work without issue previously, I really do not know what did change, looking at the recent commits nothing is suspicious.

I noticed this in PR comment (both in a thread and on the PR directly), and in review submission.

I managed to fix it with the #589, but it still seems crazy to me that I am the only one experiencing this, and I would like to pinpoint why the issue started in the first place

### Repro steps

- Open a PR and start a review on any repo
- Add a multiline comment, either directly in the PR, in a review thread, editing an existing comment, or submitting the review
- See the error `gh: Expected string or block string, but it was malformed` pop, and the update is ignored by github

### Tell us your environment
I am using NixOS unstable, config is managed through lazy, `nvim` and `gh` installed through home-manager

```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1713773202

gh version 2.55.0 (1980-01-01)
https://github.com/cli/cli/releases/tag/v2.55.0

nixpkgs: github:nixos/nixpkgs/71e91c409d1e654808b2621f28a327acfdad8dc2
```

**Comment by franckdelage** [comment]
Got exactly the same problem, with almost the same config (NVIM 0.11)

**Comment by franckdelage** [comment]
> Got exactly the same problem, with almost the same config (NVIM 0.11)

And it is now fixed!

Many thanks for the efficiency. And for this beautiful plugin :)

**Comment by pwntester** [comment]
@GuillaumeLagrange @franckdelage @usmonster I had to revert this PR since it was breaking other Octo commands, but fixed it in https://github.com/pwntester/octo.nvim/pull/597 Can you please give it a try and let me know if the issues are fixed with it?

**Comment by franckdelage** [comment]
> @GuillaumeLagrange @franckdelage @usmonster I had to revert this PR since it was breaking other Octo commands, but fixed it in https://github.com/pwntester/octo.nvim/pull/597 Can you please give it a try and let me know if the issues are fixed with it?

Will check tomorrow and let you know 🙂

**Comment by GuillaumeLagrange** [comment]
@pwntester I think github must have pulled their changes because master works for me when editing/creating multiline comments despite #589 being reverted.

#597 does not break my workflow all good to me, thanks for the ping!

**Comment by pwntester** [comment]
Thanks for the feedback @GuillaumeLagrange since it seems like GitHub reverted the changes, I dont think its urgent to get #597 merged but I think we should do soonish just in case GitHub reverts this change again. Will wait for a few more feedback and then merge it.

**Comment by franckdelage** [comment]
Sorry for the delay @pwntester , everything seems to be OK after an update this morning. LGTM.
