### ISSUE TITLE
Empty string passed to `gh` command

### ISSUE THREAD

**Issue by wd60622** [pwntester/octo.nvim#592]
## Issue Description

Type: *bug report*

Previewers for issues and prs not working proper`issue list` and `pr list` results in 

`gh: Expected NAME, actual: UNKNOWN_CHAR ("") at [49, 35]`

when using defaults_to_projects_v2 = true in the config

It seems that the project section of the query that is inserted for the previewer query contains \n characters which might be causing an issue.

### Describe what you expected to happen

Old behavior

### How to reproduce it (as minimally and precisely as possible)

0. Set defaults_to_projects_v2 = true in your config
1. `Octo issue list` or `Octo pr list`
2. 
3. 

### Tell us your environment

NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128

gh version 2.55.0 (2024-08-20)

`defaults_to_projects_v2 = true` in the config

**Comment by pwntester** [comment]
Thanks for reporting @wd60622 Seems like this is caused by #589 so reverting it for now.
