### ISSUE TITLE
Bug: Cannot create Pull Requests - Expected string or block string, but it was malformed

### ISSUE THREAD

**Issue by enrique-villarrealp** [pwntester/octo.nvim#595]
## Issue Description

*bug report*
### Describe what happened (or what feature you want)

When creating a PR through Octo, I get the following error: Expected string or block string, but it was malformed,
Using `gh pr create` works flawlessly. 

### Describe what you expected to happen

Pr gets created, and I land into the PR buffer.

### How to reproduce it (as minimally and precisely as possible)

1. Create a git branch in a repo, and commit to it.
2. Push it and use `Octo pr create` to attempt to create a PR
3. Complete the prompts 

### Tell us your environment

macOS Sonoma 14.4.1
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491

Octo - master - fd50872

### Anything else we need to know?

This error happens as well when opening an already created PR through `Octo pr list` and saving it after editing.

**Comment by nicoandresr** [comment]
This happens to me as well but it sometimes works and most of the times not with above error message :shrug:

**Comment by pwntester** [comment]
This seems related to #590 which I had to revert unfortunately. Will take a look at what escaping is needed

**Comment by pwntester** [comment]
@enrique-villarrealp @nicoandresr Can you please give #597 a try and let me know if the issues are fixed with it?

**Comment by enrique-villarrealp** [comment]
@pwntester Just tried it out with a quick test and it did work! :)

**Comment by nicoandresr** [comment]
@pwntester yes it works well! thanks :clap:

**Comment by pwntester** [comment]
Thanks!
