### ISSUE TITLE
Add comment to git diff 

### ISSUE THREAD

**Issue by tami5** [pwntester/octo.nvim#61]
:heart_eyes: this what stopping me from using github.com client. Is it possible?

**Comment by lukas-reineke** [comment]
it is possible, we are working on it
take a look at https://github.com/pwntester/octo.nvim/discussions/9

**Comment by tami5** [comment]
Nice soooo looking forward for this one, thanks @lukas-reineke

**Comment by pwntester** [comment]
yep, we are still deciding how the UX would be.

for starting a new review, you can already use `Octo review start` on a PR buffer, you wont be able to add comments yet, but that feature will be ported from @lukas-reineke `pr.nvim`

for reading review comments, you can use `Octo pr reviews` but you cant reply to comments yet, we are working on it.

**Comment by tami5** [comment]
I'll check it out @pwntester and report back there
