### ISSUE TITLE
`Octo repo url` doesn't copy GitHub Repo URL in non-octo buffers

### ISSUE THREAD

**Issue by Drew-Daniels** [pwntester/octo.nvim#628]
Thanks for making this plugin! It's really useful.

## Issue Description

Type: bug report

I have not been able to get `:Octo repo url` to successfully copy the URL of the GitHub repo that corresponds to whatever Git repo I'm in.

I have, however been able to use other commands successfully, like `:Octo pr view <pr-number>`, so I don't think it's an authentication issue.

### Describe what happened (or what feature you want)
My system clipboard keeps whatever I had last copied, instead of the GitHub URL

### Describe what you expected to happen
I expect that the URL of the GitHub repo be copied to my clipboard

### How to reproduce it (as minimally and precisely as possible)

I don't thing these specific configurations are necessary, but here is how I have everything set up on my system.

1. Install `octo.nvim` as a plugin using `lazy.nvim`
```lua
return require("lazy").setup({
  {
    "pwntester/octo.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope.nvim",
      "nvim-tree/nvim-web-devicons",
    },
  },
})
```

2. Configure `octo.nvim` as follows:

```lua
require("octo").setup({
  default_to_projects_v2 = true,
  mappings_disable_default = true,
})
``` 

3. `cd` into a local `git` repository that you have cloned from a remote repo
4. Open `nvim` and run `:Octo repo url`
5. See that the remote url of the git repo is not copied to your system clipboard

### Tell us your environment
```sh
❯ uname -a
Darwin KIPU-DDANIELS.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:35:10 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T6031 arm64
```

**Comment by wd60622** [comment]
Hi @Drew-Daniels, I often have difficulties with the clipboard as well. 

Can you confirm that you are getting logging message and it is being added to the \"+ register? `:registers +` to check.

**Comment by Drew-Daniels** [comment]
Hey @wd60622 - glad it's not just me!

Just to be sure I understand, what kind of logging message should I be looking for/where should I check for this?

I have checked the `+` register as well (this is what I had last copied, but running `:Octo repo url` didn't overwrite it)

![image](https://github.com/user-attachments/assets/61633703-b7a3-475b-80e6-abdd78e99893)

**Comment by wd60622** [comment]
Interesting. This is all that is running: 
https://github.com/pwntester/octo.nvim/blob/0adcc6d37a3cd2dae014fa5e48bee6147100c357/lua/octo/commands.lua#L1665
Can you try that in a lua script and see if it works isolated

**Comment by Drew-Daniels** [comment]
Seems to be working as expected:

![image](https://github.com/user-attachments/assets/4c4dd883-f242-4981-8ef2-fd82eb3ef387)

I'm guessing that `buffer` may be `nil`?
https://github.com/pwntester/octo.nvim/blob/0adcc6d37a3cd2dae014fa5e48bee6147100c357/lua/octo/commands.lua#L1659-L1663

**Comment by wd60622** [comment]
The error message is just wrapper around vim notify. Try `:lua require(\"octo.utils\").info(\"Some info\")` to see what it would look like.

Yes, It seems to require being in an octo buffer to work which doesn't make sense to get repo URL, so seems like a bug. 

Would you want to make a PR to fix it?
