### ISSUE TITLE
Merging PR from picker displays success message even if it failed

### ISSUE THREAD

**Issue by macovsky** [pwntester/octo.nvim#657]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

When merging not mergeable PR (checks haven't been completed or they have been unsuccessful, no review etc.) from picker (telescope in my case) I get `Merged PR 3502!` displayed nevertheless.

### Describe what you expected to happen

Even rough error message would have been better, like the one with `Octo pr merge`:

```
X Pull request .../...#3502 is not mergeable: the merge commit cannot be cleanly created.
```

### How to reproduce it (as minimally and precisely as possible)

1. Find PR which is not mergeable
2. Select it in `Octo pr search` for example (don't open)
3. Press "merge pr" binding (`<C-r>` by default)

**Comment by wd60622** [comment]
Hi @macovsky 
Interested in making a PR?

**Comment by macovsky** [comment]
sure, I’ll try.
