### ISSUE TITLE
vertical/horizontal splits

### ISSUE THREAD

**Issue by tami5** [pwntester/octo.nvim#69]
Hey @pwntester, I was trying to open an issue in vertical split and I got the following error:

```lua
E5108: Error executing lua vim/shared.lua:64: s: expected string, got number
stack traceback:
        vim/shared.lua:64: in function 'gsplit'
        vim/shared.lua:111: in function 'split'
        ...packer/opt/telescope.nvim/lua/telescope/actions/init.lua:96: in function 'func'
        ...k/packer/opt/telescope.nvim/lua/telescope/actions/mt.lua:14: in function '_goto_file_se`
```

Other:
- PREVIEW number printed in the command.
- is there away to switch gh to use upstream instead of origin which is currently a fork 

Thanks

**Comment by pwntester** [comment]
Thanks for reporting, fixed in https://github.com/pwntester/octo.nvim/commit/32420c86c33b9eb4a503be1d2398ea0c938d0d92

Can you file a new issue for "is there away to switch gh to use upstream instead of origin which is currently a fork"? wouldnt be enough to do `Octo issue list foo/bar` where `foo/bar` is the name of the upstream repo?

**Comment by tami5** [comment]
> fixed in 32420c8

Thanks a lot


> Octo issue list foo/bar

oh that is enough, I guess it would be smarter if we determined if the current repo is the fork and run foo/bar instead. like if upstream exists. But yes that should be enough for now

**Comment by pwntester** [comment]
> oh that is enough, I guess it would be smarter if we determined if the current repo is the fork and run foo/bar instead. like if upstream exists. But yes that should be enough for now

That was actually considered here https://github.com/pwntester/octo.nvim/blob/master/lua/octo/util.lua#L33, but `upstream` is just a convention and one could use any other name

If you just want to use it for the issues/pr menus, we could just change the call here https://github.com/pwntester/octo.nvim/blob/master/lua/octo/menu.lua#L215
so one of the opts is used to select the remote

**Comment by tami5** [comment]
hmmm :thinking:, It would be good for issues/pr, but I'm not sure if there's anything else. how about user option that say if upstream exists then use it else origin? 

:laughing: I should've just opened new issue

**Comment by pwntester** [comment]
I added a new setting `g:octo_remote_order` which is an array with the name of remotes to try for resolving the repo at CWD. default is `["upstream", "origin"]`

**Comment by tami5** [comment]
😍😍😍 oh thats smart, thanks so much @pwntester
