### ISSUE TITLE
Add support for PR reviews

### ISSUE THREAD

**Issue by pwntester** [pwntester/octo.nvim#71]
This is already started in `Octo review start` which will currently:
- create new tab
- open qf with all changed files and a special handler so selecting a qf entry will split the main window in two showing the fugitive diffs for the selected file.

Work to do:
- [x] new range command (eg: `OctoReviewComment`) to add a new comment on either side of the diff.
  - [x] shows a new buffer where the user can enter the new comment. On `:w`:
    - [x] maps the fugitive buffer lines with the diff hunk lines
    - [x] the buffer content and the lines it correspond to are added to a list of pending comments 
    - [x] lines are marked with some special highlight/signs
- [x] new `Octo review comments` command will show a telescope menu that let you review update and delete review comments.
  - [ ] <c-d> delete the comment
  - [x] <CR> goes to the file/line
  - [x] <c-u> open comment in buffer and allow user to modify it
- [x] new `Octo review submit` command will show a new buffer to enter review body. On `:w`:
    - [x] a menu is shown to choose between: Comment, Request Changes or Approve.
    - [x] the GH api to create the new review
  	- [x] the review tab and buffers are closed 

* all comment buffer are opened in an horizontal split from qf (whole screen width) rather than any sort of float since reviewers may want to move between buffers/wins to copy/paste code into the new comment.

@lukas-reineke @PatOConnor43 @tami5 any feedback is welcome!

**Comment by entropitor** [comment]
>  delete the comment

is the only unchecked item on this list. Is this being worked on / tracked in a separate issue?

**Comment by pwntester** [comment]
Not yet, I just forgot. Please file a new issue and will look at it asap
