### ISSUE TITLE
[BUG] Timeout option doesn't affect timeout of gh requests

### ISSUE THREAD

**Issue by kapral18** [pwntester/octo.nvim#737]
## Issue Description

Type: *bug report*

### Describe what happened
When settings `timeout` explicitly. For example to 55000ms for large projects and large PRs,
I still get 5s timeout error but now coming from plenary layer
![image](https://github.com/user-attachments/assets/2beb8cb0-f01e-4879-ba76-60a854b3b135)

### Describe what you expected to happen

Timeout should be passed into plenary as well

### How to reproduce it (as minimally and precisely as possible)

1. Make sure you are not on the pr branch
2. `Octo pr edit <number>`
3. `Octo review start`

### Tell us your environment
MacOS 15.2

**Comment by wd60622** [comment]
Thats for reporting. Would you like to make a PR?

**Comment by kapral18** [comment]
@wd60622 https://github.com/pwntester/octo.nvim/pull/738
