### ISSUE TITLE
split/vsplit doesn't work

### ISSUE THREAD

**Issue by tami5** [pwntester/octo.nvim#76]
`<c-v>/<c-s>` doesn't work for me. `<cr>` seems to be the only one working 

Also, trying to open in the browser `<c-b>` for prs results in 

```lua
E5108: Error executing lua vim/shared.lua:64: s: expected string, got number
stack traceback:
        vim/shared.lua:64: in function 'gsplit'
        vim/shared.lua:111: in function 'split'
        ...re/nvim/site/pack/packer/opt/octo.nvim/lua/octo/menu.lua:134: in function 'key_func'
        ...ack/packer/opt/telescope.nvim/lua/telescope/mappings.lua:204: in function 'executeP
```

**Comment by pwntester** [comment]
Thanks for reporting @tami5 

`<c-b>` should work now

What is `<c-s>` for? `<c-x>` and `<c-v>` work for me.

**Comment by tami5** [comment]
Oh srry it's a remap of `<c-x>`. `C-b` works now but the rest doesn't still. It just open in current split

**Comment by pwntester** [comment]
thats weird, Im replacing telescope commands which I think is the right way to do it:

https://github.com/pwntester/octo.nvim/blob/master/lua/octo/menu.lua#L231-L234

I cannot reproduce it so cannot debug it, can you check https://github.com/pwntester/octo.nvim/blob/master/lua/octo/menu.lua#L56-L69 and see if there is something which cause that behaviour for you?

**Comment by tami5** [comment]
I think I believe I found the issue, let me test and get back to you.

**Comment by pwntester** [comment]
Anything I can help you with @tami5 ?

**Comment by tami5** [comment]
Hmm let finish up a project I've been working on for the last two week and return to this issue later. Thanks @pwntester
