### ISSUE TITLE
question: how to change diff number colour

### ISSUE THREAD

**Issue by elianiva** [pwntester/octo.nvim#77]
Hi there! I love this plugin so far, though I have one little question. How do I change the diff number colour? I can change it from `Diff{Add,Delete,Change}` highlight group but if I do that, it would affect the diffmode highlights as well. I've tried changing `OctoNvimBubble{Red,Green}` but I don't think that's the one because it doesn't have any effect. Thanks in advance!
 
 
![image](https://user-images.githubusercontent.com/51877647/105663804-c173d080-5f05-11eb-8dcd-a3312c551fa4.png)

 -- this issue was made using octo.nvim :laughing:

**Comment by pwntester** [comment]
Thanks! I have created some new hl groups and make them default to `DiffXXX` instead of using these directly. You can now set your own `OctoNvimPullAdditions`, `OctoNvimPullDeletions` and `OctoNvimPullModifications`
