### ISSUE TITLE
Error starting review

### ISSUE THREAD

**Issue by aareman** [pwntester/octo.nvim#84]
Kudos on the app, it looks like it will help me out a ton :smile: 

I'm trying to figure out how it works and running into a few issues. 

# Issue 1
Ran
```vim
:Octo pr list <ORG>/<REPO> states=OPEN
" Selected a PR
:Octo pr checkout
:Octo review start
```
![image](https://user-images.githubusercontent.com/10500823/107726877-178f9480-6cb8-11eb-9644-3be46bd27f12.png)

# Issue 2
```vim
:Octo pr list <ORG>/<REPO> states=OPEN
" Selected a PR
:Octo pr checkout
:Octo pr files 
" After i select one I get...
```
![image](https://user-images.githubusercontent.com/10500823/107727199-bae0a980-6cb8-11eb-8b66-7b7fed0c99c8.png)

# vimrc
```vim
" ...
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'pwntester/octo.nvim'
"...
lua require('telescope').load_extension('octo')
```

Any ideas would be most appreciated

# info
![image](https://user-images.githubusercontent.com/10500823/107727376-27f43f00-6cb9-11eb-8d1e-cb75f06d2791.png)

![image](https://user-images.githubusercontent.com/10500823/107727494-76a1d900-6cb9-11eb-9ade-c7e048039427.png)

**Comment by pwntester** [comment]
Hi! thanks for reporting the issues. The PR review features are still in "beta" and definitly appreciate any bug reports and feedback.

Re: Issue 1:
It may be the case that `Octo pr checkout` failed to switch the branch to the PR one. Does the error makes sense to you? was that the branch you were in before trying tp checkout the PR one? Can you please check `:messages` after running the `Octo pr checkout` command to see if there were any problems switching branches? Can you try checking out the PR branch with `:!gh pr checkout`?

Re: Issue 2:
This seem to be a Telescope related bug. Do your see the file diff in the preview buffer before selecting the entry?

**Comment by aareman** [comment]
For beta its pretty polished! I do a lot of github PR reviews cross projects for work, and a tool like this is a God send. If there is anything I can do to help, would love to help out.

re 1. the pr checkout worked, my working directory was changed to the correct branch and there was a message saying so as well in the vim messages

re 2. no preview shown

**Comment by pwntester** [comment]
> For beta its pretty polished! I do a lot of github PR reviews cross projects for work, and a tool like this is a God send. If there is anything I can do to help, would love to help out.

Thanks! any feedback is welcome, from bug reports, to UX feedback to PRs!

re1: it seem like you current branch is `renameabranchanditsreflog..` while the PR head ref is `AR-447`. Which one is the incorrect?

re2: can you try https://github.com/pwntester/octo.nvim/pull/90 and paste here the output of `:messages` after popping up the changed files menu?

**Comment by aareman** [comment]
re1: The actual branch in git is AR-447. that's what I get with git status.

re2: yes I'll get that to you

**Comment by pwntester** [comment]
re1: I may know whats going on. `git branch --show-current` only works with git 2.22 and above and you may be using an older version? Seems like I can also get the branch name with `git rev-parse --abbrev-ref HEAD` in any git version. I have tried this approach in the `debug_84_2` branch. Can you give it a try and let me know if that works for you?

**Comment by aareman** [comment]
yep I think that was it. As an aside, I don't know if you want to give an escape hatch to skip git hooks. I have a git post-checkout hook in my repo that does a docker pull to update images, but I don't need that to run per se.

![image](https://user-images.githubusercontent.com/10500823/108092344-9f73f680-704a-11eb-84a4-c22c397d5ebb.png)

**Comment by aareman** [comment]
A second issue now coming across is that when running `:Octo pr reviews` (from a pr buffer) I get

![image](https://user-images.githubusercontent.com/10500823/108092704-f8438f00-704a-11eb-8628-c26ee79b2ec4.png)

I think the issue is that whatever method is being used to determine the repo `<org>/<repo>` is returning nil. I had that with `:Octo pr list` where I needed to specify the org/repo manually. I'm on git 2.17 I think

**Comment by aareman** [comment]
same error also happens with `:Octo review start`

**Comment by aareman** [comment]
I updated git to `2.30` same issue persists.

**Comment by aareman** [comment]
RESOLVED!! My `git-config` was being overriden by a custom `git` tool my company has, I disabled that and it seems to be working now. Thank you for your hard work. I'll let you know as I use it :smile:

**Comment by pwntester** [comment]
Great! So everything is working now? Also the issue with the preview buffers?

**Comment by aareman** [comment]
Yes. Thank you
