### ISSUE TITLE
command to do Octo pr edit 63 | Octo pr checkout | Octo review start

### ISSUE THREAD

**Issue by tami5** [pwntester/octo.nvim#85]
Hey, @pwntester sometimes it would be better to review a pr without checking it out, or to have a single command to start review session

**Comment by pwntester** [comment]
> Hey, @pwntester sometimes it would be better to review a pr without checking it out

I will implement a review mode based on diffhunks only. It will not require checking out the PR or even have the repo locally. But it will miss the context provided by having the PR checkout.

> or to have a single command to start review session

I can implement `Octo review pr <repo> <number>`. But maybe cuatom mappings are enough

**Comment by tami5** [comment]
I'm thinking Octo should have full command, I hate doing tab category tab action . What you think if I write commands like :+1: 
```
OctoCreatePr
OctoCreateIssue
OctoReviewPr
```

In addition of OctoPr..., OctoIssue...

I think this is a bit a vim way, you can search them in command history easily

**Comment by pwntester** [comment]
That was the initial approach but ended up in a command explosion with dozens of commands. I prefer the current approach since it allows users to define their custom commands and alias.

**Comment by pwntester** [comment]
Will close thisnone for now, thanks for the suggestion @tami5
