### ISSUE TITLE
skip pushing a comment if body is empty

### ISSUE THREAD

**Issue by tami5** [pwntester/octo.nvim#86]
Hey @pwntester I had to do some debugging after review won't get submitted due to gh returning `gh: Body can't be blank`. Basically I had to manually do this and it worked (thank god :laughing: )

```lua
print(vim.inspect(require'octo.reviews'.review_comments))
-- find a key with empty body
require'octo.reviews'.review_comments['key'] = nil

```

**Comment by pwntester** [comment]
Thanks @tami5, should be fixed by now, please reopen otherwise
