### ISSUE TITLE
Feature request: tracking of users opened repos

### ISSUE THREAD

**Issue by tami5** [pwntester/octo.nvim#89]
- Requires 'sql.nvim'
- Users can browse all repos open in their neovim
- Picker for doing actions on these repos, new pr, new issue, checkout different branch ....

**Comment by pwntester** [comment]
I like the idea, something similar to nvim-telescope-projects. However, I dont want to introduce additional dependencies at this point. Maybe we can implement it as an extension?

**Comment by tami5** [comment]
Yah sure, I'll keep this issue open, maybe next week I'd work on it. But it should be simple to implement, 

- machinism to insert the git repos
- table schema with meta data information 
- picker that query the sql table and sort based on keys.
- function that call octo functions against selection

**Comment by pwntester** [comment]
This may be a good idea for an extension or complementary plugin, but Im closing this for now since Im not planning on implementing it in the near future.
