### ISSUE TITLE
online reviews

### ISSUE THREAD

**Issue by tami5** [pwntester/octo.nvim#93]
Hey, I'm having this issue with start review, I forget to switch/checkout the pr before start review which results in `Not in PR branch. Expected X, got Y`.
Not sure if auto_switch option would be the right workaround for this problem, or enabling without swiching branch would be better, what do you think? 

Thanks

**Comment by pwntester** [comment]
Thanks @tami5 Im working on a new review implementation which does not depend on local files. This should solve your problems and lower the barrier to use Octo for PR reviews. Stay tuned!

**Comment by pwntester** [comment]
Implemented in #94, please give it a try :)

**Comment by tami5** [comment]
Sure thing, I'll test them out tom
