### ISSUE TITLE
Broken layout for PR reviews?

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#95]
Hey, 
I just tried my first real PR review with Octo. Therefore I followed the first steps in the README tutorial. After typing `:Octo review start` I get the following result. It kinda looks broken to me. How to fix this? Because this way I can't review. :laughing: 

![octo](https://user-images.githubusercontent.com/12543647/108679621-1bf45280-74ed-11eb-8257-6c392ccab160.png)

**Comment by pwntester** [comment]
hmm, thats weird, the layout vertical split is created using `leftabove vert diffsplit <other version>`. Can you try opening any file and doing `leftabove vert diffsplit %` to see how it diffs against itself and what the layout is?

**Comment by weilbith** [comment]
This works perfectly fine. Getting 50/50 view. :shrug:

**Comment by pwntester** [comment]
I'm rewriting that code as part of #94 
Can you try that branch and see if you get the 50/50 layout there?

**Comment by weilbith** [comment]
Yes, works for me. Thank you very much! :hugs:
