### ISSUE TITLE
Reload active issue/PR buffer with e!

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#97]
If you are in a big and intensive PR discussion with multiple threads, it would be cool if you could keep the PR buffer open and reload it to see a response by another user (while you have respond in other threads maybe). Not sure if this would work with fetching the autocommand when the use types `:e!`?
This might be related to the idea in #59 to have folds for review conversations in the PR buffer.

**Comment by pwntester** [comment]
You can currently reload the buffer with `Octo issue/pr reload` or just `<c-r>` but I will look into the `e!` idea to make it more vim-ish.

As for including review threads in the main PR buffer. I think we can add a configuration setting to enable it. This should be independent of having folds for octo comments/threads. Please file a different issue for each of these two enhacement requests

**Comment by weilbith** [comment]
> You can currently reload the buffer with Octo issue/pr reload or just <c-r> but I will look into the e! idea to make it more vim-ish.

Thank you very much! Sorry that I missed that. :expressionless:

**Comment by tami5** [comment]
Interesting I didn't know we can do that nice

**Comment by weilbith** [comment]
Sorry mistake. Missed that this is now about the idea to make it more vimish with `:e!` :speak_no_evil:

**Comment by tami5** [comment]
How about step further and let octo.nvim check every 5 seconds async, and update the buffer if current data mismatch the remote data.

**Comment by weilbith** [comment]
> How about step further and let octo.nvim check every 5 seconds async, and update the buffer if current data mismatch the remote data. 

I don't think that's a good idea. As we there is this concept that the buffer is editable and changes get pushed via the API, this could just lead to often to ugly conflicts. I mean there should be no conflicts, but at least some merging strategy would be required.

**Comment by tami5** [comment]
Oh yah increases complexity at this stage, perhaps later down the line or put into  todo list with low priority. @pwntester how about a project and we link issues of that sort to it.

**Comment by pwntester** [comment]
It could make the call and only reload the buffer if its not modified. There can be some cursor position glitches though

**Comment by pwntester** [comment]
LOL, it turns out `e!` already works with current `BufReadCmd` implementation :laugh:
