### ISSUE TITLE
Feature request - add hover window for issue/PR numbers on CursorHold

### ISSUE THREAD

**Issue by weilbith** [pwntester/octo.nvim#99]
Taken from [here].
The title basically states it. But in the web UI of GitHub you can hover over issue and PR numbers (plus users, also this isn't that interesting) which will show a summary of this object. This is incredibly useful when you read a issue or PR and see such a reference. You usually don't want to interrupt your flow and searching this issue and open it, than search the old issue and scroll to where you left earlier.

**Comment by weilbith** [comment]
Extension: hover over reactions lists users

**Comment by pwntester** [comment]
Been implemented in #129

Some screenshots for comments and feedback:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/125701/110612300-579b4780-8190-11eb-8dd6-4181c0d84cde.png">

<img width="914" alt="image" src="https://user-images.githubusercontent.com/125701/110612318-5cf89200-8190-11eb-9b00-31b69b42a542.png">

<img width="884" alt="image" src="https://user-images.githubusercontent.com/125701/110612343-62ee7300-8190-11eb-812f-d2ca93078efa.png">

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/125701/110612438-7ac5f700-8190-11eb-9bfb-3c132b62fd12.png">

**Comment by pwntester** [comment]
sample query for comment reactions:

```
{
  node(id: "%s") {
    ... on PullRequestReviewComment {
      reactionGroups {
        content
        users(last: 100) {
          nodes {
            login
          }
        }
      }
    }
    ... on PullRequestReview {
      reactionGroups {
        content
        users(last: 100) {
          nodes {
            login
          }
        }
      }
    }
    ... on IssueComment {
      reactionGroups {
        content
        users(last: 100) {
          nodes {
            login
          }
        }
      }
    }
  }
}
```

**Comment by pwntester** [comment]
sample query for user information:

```
{
  user(login: "%s") {
    login
    bio
    company
    followers(first: 1) {
      totalCount
    }
    following(first: 1) {
      totalCount
    }
    hovercard {
      contexts {
        message
      }
    }
    hasSponsorsListing
    isEmployee
    isViewer
    location
    organizations(last: 5) {
      nodes {
        name
      }
    }
    name
    status {
      emoji
      message
    }
    twitterUsername
    websiteUrl
  }
}
```

**Comment by weilbith** [comment]
Reactions are virtual text, aren't they? This means the user can't move the cursor on them. Or do I miss something?

**Comment by pwntester** [comment]
They are, but I planned to show a table with all reactions/users if hovering over the reactions line.
Alternatively we can use an overlay which should allow users to move around the line. On hold, we should be able to resolve what reaction in under the cursor

**Comment by pwntester** [comment]
Added reactions popup:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/125701/111628071-163e1400-87f0-11eb-8615-44befb62d14b.png">

unaligned border seems to be a bug in neovim ...

**Comment by pwntester** [comment]
User profile exmaples:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/125701/111709840-ba53a980-8848-11eb-9ab6-52aa56e42471.png">

<img width="819" alt="image" src="https://user-images.githubusercontent.com/125701/111709855-c0e22100-8848-11eb-9e1f-6e6faa7f609d.png">

<img width="510" alt="image" src="https://user-images.githubusercontent.com/125701/111709871-c50e3e80-8848-11eb-8333-79b2d657df97.png">

<img width="361" alt="image" src="https://user-images.githubusercontent.com/125701/111709908-d3f4f100-8848-11eb-83c8-14f8a5bf3e23.png">

<img width="532" alt="image" src="https://user-images.githubusercontent.com/125701/111709932-e0794980-8848-11eb-95a5-286a80a1ce97.png">

<img width="710" alt="image" src="https://user-images.githubusercontent.com/125701/111710079-3817b500-8849-11eb-9434-70e707e0a589.png">

**Comment by weilbith** [comment]
Amazing work! This issue is so damn perfectly fulfilled. 😬
